# Generated by Django 5.1.15 on 2026-09-28 11:42

import apps.loja.models.base
import apps.loja.models.pedido
import django.core.serializers.json
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rotulos_ptbr'),
        ('loja', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clienteendereco',
            options={'verbose_name': 'endereco do cliente', 'verbose_name_plural': 'enderecos do cliente'},
        ),
        migrations.AlterModelOptions(
            name='cupom',
            options={'verbose_name': 'cupom', 'verbose_name_plural': 'cupons'},
        ),
        migrations.AlterModelOptions(
            name='entregapedido',
            options={'ordering': ['id'], 'verbose_name': 'entrega', 'verbose_name_plural': 'entregas'},
        ),
        migrations.AlterModelOptions(
            name='historicalclienteendereco',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical endereco do cliente', 'verbose_name_plural': 'historical enderecos do cliente'},
        ),
        migrations.AlterModelOptions(
            name='historicalcupom',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical cupom', 'verbose_name_plural': 'historical cupons'},
        ),
        migrations.AlterModelOptions(
            name='historicalentregapedido',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical entrega', 'verbose_name_plural': 'historical entregas'},
        ),
        migrations.AlterModelOptions(
            name='historicalitembundle',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical componente do bundle', 'verbose_name_plural': 'historical componentes do bundle'},
        ),
        migrations.AlterModelOptions(
            name='historicalitempedido',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical item do pedido', 'verbose_name_plural': 'historical itens do pedido'},
        ),
        migrations.AlterModelOptions(
            name='historicalmidiaproduto',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical midia do produto', 'verbose_name_plural': 'historical midias do produto'},
        ),
        migrations.AlterModelOptions(
            name='historicalpagamentopedido',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical pagamento', 'verbose_name_plural': 'historical pagamentos'},
        ),
        migrations.AlterModelOptions(
            name='historicaltipovariante',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical tipo de variante', 'verbose_name_plural': 'historical tipos de variante'},
        ),
        migrations.AlterModelOptions(
            name='historicalvalordavarianteproduto',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical valor da variante', 'verbose_name_plural': 'historical valores da variante'},
        ),
        migrations.AlterModelOptions(
            name='historicalvalorvariante',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical valor de variante', 'verbose_name_plural': 'historical valores de variante'},
        ),
        migrations.AlterModelOptions(
            name='historicalvarianteproduto',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical variante', 'verbose_name_plural': 'historical variantes'},
        ),
        migrations.AlterModelOptions(
            name='itembundle',
            options={'verbose_name': 'componente do bundle', 'verbose_name_plural': 'componentes do bundle'},
        ),
        migrations.AlterModelOptions(
            name='itempedido',
            options={'ordering': ['id'], 'verbose_name': 'item do pedido', 'verbose_name_plural': 'itens do pedido'},
        ),
        migrations.AlterModelOptions(
            name='midiaproduto',
            options={'ordering': ['posicao', 'id'], 'verbose_name': 'midia do produto', 'verbose_name_plural': 'midias do produto'},
        ),
        migrations.AlterModelOptions(
            name='pagamentopedido',
            options={'ordering': ['id'], 'verbose_name': 'pagamento', 'verbose_name_plural': 'pagamentos'},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['-created_at'], 'verbose_name': 'pedido', 'verbose_name_plural': 'pedidos'},
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['-created_at'], 'verbose_name': 'produto', 'verbose_name_plural': 'produtos'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['nome'], 'verbose_name': 'tag', 'verbose_name_plural': 'tags'},
        ),
        migrations.AlterModelOptions(
            name='tipovariante',
            options={'ordering': ['posicao', 'id'], 'verbose_name': 'tipo de variante', 'verbose_name_plural': 'tipos de variante'},
        ),
        migrations.AlterModelOptions(
            name='valordavarianteproduto',
            options={'verbose_name': 'valor da variante', 'verbose_name_plural': 'valores da variante'},
        ),
        migrations.AlterModelOptions(
            name='valorvariante',
            options={'ordering': ['posicao', 'id'], 'verbose_name': 'valor de variante', 'verbose_name_plural': 'valores de variante'},
        ),
        migrations.AlterModelOptions(
            name='varianteproduto',
            options={'ordering': ['posicao', 'id'], 'verbose_name': 'variante', 'verbose_name_plural': 'variantes'},
        ),
        migrations.AlterField(
            model_name='categoria',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='criado por'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='alterado por'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='criado por'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='alterado por'),
        ),
        migrations.AlterField(
            model_name='clienteendereco',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='criado por'),
        ),
        migrations.AlterField(
            model_name='clienteendereco',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='alterado por'),
        ),
        migrations.AlterField(
            model_name='cupom',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='criado por'),
        ),
        migrations.AlterField(
            model_name='cupom',
            name='currency',
            field=models.CharField(default='BRL', max_length=3, verbose_name='moeda'),
        ),
        migrations.AlterField(
            model_name='cupom',
            name='customer_eligibility',
            field=models.CharField(choices=[('all', 'Todos'), ('specific_customers', 'Clientes especificos'), ('customer_tags', 'Tags de clientes')], default='all', max_length=30, verbose_name='clientes elegiveis'),
        ),
        migrations.AlterField(
            model_name='cupom',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'Percentual'), ('fixed_amount', 'Valor fixo'), ('free_shipping', 'Frete gratis')], max_length=20, verbose_name='tipo de desconto'),
        ),
        migrations.AlterField(
            model_name='cupom',
            name='ends_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='termino'),
        ),
        migrations.AlterField(
            model_name='cupom',
            name='first_order_only',
            field=models.BooleanField(default=False, verbose_name='so no primeiro pedido'),
        ),
        migrations.AlterField(
            model_name='cupom',
            name='free_shipping',
            field=models.BooleanField(default=False, verbose_name='frete gratis'),
        ),
        migrations.AlterField(
            model_name='cupom',
            name='metadata',
            field=apps.loja.models.base.JSONDecimalField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='dados extras'),
        ),
        migrations.AlterField(
            model_name='cupom',
            name='minimum_quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='quantidade minima'),
        ),
        migrations.AlterField(
            model_name='cupom',
            name='minimum_requirement',
            field=models.CharField(choices=[('none', 'Nenhum'), ('subtotal', 'Subtotal'), ('quantity', 'Quantidade')], default='none', max_length=20, verbose_name='requisito minimo'),
        ),
        migrations.AlterField(
            model_name='cupom',
            name='minimum_subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='subtotal minimo'),
        ),
        migrations.AlterField(
            model_name='cupom',
            name='once_per_order',
            field=models.BooleanField(default=True, verbose_name='uma vez por pedido'),
        ),
        migrations.AlterField(
            model_name='cupom',
            name='product_eligibility',
            field=models.CharField(choices=[('all', 'Todos'), ('specific_products', 'Produtos especificos'), ('specific_variants', 'Variantes especificas'), ('categories', 'Categorias'), ('product_tags', 'Tags de produtos')], default='all', max_length=30, verbose_name='produtos elegiveis'),
        ),
        migrations.AlterField(
            model_name='cupom',
            name='stacking_policy',
            field=models.CharField(choices=[('deny', 'Nao combina com outros cupons'), ('allow', 'Combina com outros cupons')], default='deny', max_length=30, verbose_name='combinacao com outros cupons'),
        ),
        migrations.AlterField(
            model_name='cupom',
            name='starts_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='inicio'),
        ),
        migrations.AlterField(
            model_name='cupom',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='alterado por'),
        ),
        migrations.AlterField(
            model_name='cupom',
            name='usage_count',
            field=models.PositiveIntegerField(default=0, verbose_name='usos'),
        ),
        migrations.AlterField(
            model_name='cupom',
            name='usage_limit',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='limite de usos'),
        ),
        migrations.AlterField(
            model_name='cupom',
            name='usage_limit_per_customer',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='limite de usos por cliente'),
        ),
        migrations.AlterField(
            model_name='cupom',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='valor'),
        ),
        migrations.AlterField(
            model_name='entregapedido',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='criado por'),
        ),
        migrations.AlterField(
            model_name='entregapedido',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='entregue em'),
        ),
        migrations.AlterField(
            model_name='entregapedido',
            name='metadata',
            field=apps.loja.models.base.JSONDecimalField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='dados extras'),
        ),
        migrations.AlterField(
            model_name='entregapedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='loja.pedido', verbose_name='pedido'),
        ),
        migrations.AlterField(
            model_name='entregapedido',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='enviado em'),
        ),
        migrations.AlterField(
            model_name='entregapedido',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('in_transit', 'Em transito'), ('delivered', 'Entregue'), ('returned', 'Devolvido')], default='pending', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='entregapedido',
            name='tracking_company',
            field=models.CharField(blank=True, max_length=100, verbose_name='transportadora'),
        ),
        migrations.AlterField(
            model_name='entregapedido',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='codigo de rastreio'),
        ),
        migrations.AlterField(
            model_name='entregapedido',
            name='tracking_url',
            field=models.URLField(blank=True, verbose_name='link de rastreio'),
        ),
        migrations.AlterField(
            model_name='entregapedido',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='alterado por'),
        ),
        migrations.AlterField(
            model_name='historicalcategoria',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por'),
        ),
        migrations.AlterField(
            model_name='historicalcategoria',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='alterado por'),
        ),
        migrations.AlterField(
            model_name='historicalcliente',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por'),
        ),
        migrations.AlterField(
            model_name='historicalcliente',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='alterado por'),
        ),
        migrations.AlterField(
            model_name='historicalclienteendereco',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por'),
        ),
        migrations.AlterField(
            model_name='historicalclienteendereco',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='alterado por'),
        ),
        migrations.AlterField(
            model_name='historicalcupom',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por'),
        ),
        migrations.AlterField(
            model_name='historicalcupom',
            name='currency',
            field=models.CharField(default='BRL', max_length=3, verbose_name='moeda'),
        ),
        migrations.AlterField(
            model_name='historicalcupom',
            name='customer_eligibility',
            field=models.CharField(choices=[('all', 'Todos'), ('specific_customers', 'Clientes especificos'), ('customer_tags', 'Tags de clientes')], default='all', max_length=30, verbose_name='clientes elegiveis'),
        ),
        migrations.AlterField(
            model_name='historicalcupom',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'Percentual'), ('fixed_amount', 'Valor fixo'), ('free_shipping', 'Frete gratis')], max_length=20, verbose_name='tipo de desconto'),
        ),
        migrations.AlterField(
            model_name='historicalcupom',
            name='ends_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='termino'),
        ),
        migrations.AlterField(
            model_name='historicalcupom',
            name='first_order_only',
            field=models.BooleanField(default=False, verbose_name='so no primeiro pedido'),
        ),
        migrations.AlterField(
            model_name='historicalcupom',
            name='free_shipping',
            field=models.BooleanField(default=False, verbose_name='frete gratis'),
        ),
        migrations.AlterField(
            model_name='historicalcupom',
            name='metadata',
            field=apps.loja.models.base.JSONDecimalField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='dados extras'),
        ),
        migrations.AlterField(
            model_name='historicalcupom',
            name='minimum_quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='quantidade minima'),
        ),
        migrations.AlterField(
            model_name='historicalcupom',
            name='minimum_requirement',
            field=models.CharField(choices=[('none', 'Nenhum'), ('subtotal', 'Subtotal'), ('quantity', 'Quantidade')], default='none', max_length=20, verbose_name='requisito minimo'),
        ),
        migrations.AlterField(
            model_name='historicalcupom',
            name='minimum_subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='subtotal minimo'),
        ),
        migrations.AlterField(
            model_name='historicalcupom',
            name='once_per_order',
            field=models.BooleanField(default=True, verbose_name='uma vez por pedido'),
        ),
        migrations.AlterField(
            model_name='historicalcupom',
            name='product_eligibility',
            field=models.CharField(choices=[('all', 'Todos'), ('specific_products', 'Produtos especificos'), ('specific_variants', 'Variantes especificas'), ('categories', 'Categorias'), ('product_tags', 'Tags de produtos')], default='all', max_length=30, verbose_name='produtos elegiveis'),
        ),
        migrations.AlterField(
            model_name='historicalcupom',
            name='stacking_policy',
            field=models.CharField(choices=[('deny', 'Nao combina com outros cupons'), ('allow', 'Combina com outros cupons')], default='deny', max_length=30, verbose_name='combinacao com outros cupons'),
        ),
        migrations.AlterField(
            model_name='historicalcupom',
            name='starts_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='inicio'),
        ),
        migrations.AlterField(
            model_name='historicalcupom',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='alterado por'),
        ),
        migrations.AlterField(
            model_name='historicalcupom',
            name='usage_count',
            field=models.PositiveIntegerField(default=0, verbose_name='usos'),
        ),
        migrations.AlterField(
            model_name='historicalcupom',
            name='usage_limit',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='limite de usos'),
        ),
        migrations.AlterField(
            model_name='historicalcupom',
            name='usage_limit_per_customer',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='limite de usos por cliente'),
        ),
        migrations.AlterField(
            model_name='historicalcupom',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='valor'),
        ),
        migrations.AlterField(
            model_name='historicalentregapedido',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por'),
        ),
        migrations.AlterField(
            model_name='historicalentregapedido',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='entregue em'),
        ),
        migrations.AlterField(
            model_name='historicalentregapedido',
            name='metadata',
            field=apps.loja.models.base.JSONDecimalField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='dados extras'),
        ),
        migrations.AlterField(
            model_name='historicalentregapedido',
            name='pedido',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='loja.pedido', verbose_name='pedido'),
        ),
        migrations.AlterField(
            model_name='historicalentregapedido',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='enviado em'),
        ),
        migrations.AlterField(
            model_name='historicalentregapedido',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('in_transit', 'Em transito'), ('delivered', 'Entregue'), ('returned', 'Devolvido')], default='pending', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='historicalentregapedido',
            name='tracking_company',
            field=models.CharField(blank=True, max_length=100, verbose_name='transportadora'),
        ),
        migrations.AlterField(
            model_name='historicalentregapedido',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='codigo de rastreio'),
        ),
        migrations.AlterField(
            model_name='historicalentregapedido',
            name='tracking_url',
            field=models.URLField(blank=True, verbose_name='link de rastreio'),
        ),
        migrations.AlterField(
            model_name='historicalentregapedido',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='alterado por'),
        ),
        migrations.AlterField(
            model_name='historicalitembundle',
            name='bundle_product',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='loja.produto', verbose_name='produto bundle'),
        ),
        migrations.AlterField(
            model_name='historicalitembundle',
            name='component_variant',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='loja.varianteproduto', verbose_name='componente'),
        ),
        migrations.AlterField(
            model_name='historicalitembundle',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por'),
        ),
        migrations.AlterField(
            model_name='historicalitembundle',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='quantidade'),
        ),
        migrations.AlterField(
            model_name='historicalitembundle',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='alterado por'),
        ),
        migrations.AlterField(
            model_name='historicalitempedido',
            name='classe_fiscal',
            field=models.CharField(blank=True, max_length=100, verbose_name='classe fiscal'),
        ),
        migrations.AlterField(
            model_name='historicalitempedido',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por'),
        ),
        migrations.AlterField(
            model_name='historicalitempedido',
            name='id_variacao',
            field=models.PositiveBigIntegerField(default=0, verbose_name='id da variacao'),
        ),
        migrations.AlterField(
            model_name='historicalitempedido',
            name='impostos',
            field=apps.loja.models.base.JSONDecimalField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='impostos'),
        ),
        migrations.AlterField(
            model_name='historicalitempedido',
            name='nome',
            field=models.CharField(blank=True, max_length=255, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='historicalitempedido',
            name='pedido',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='loja.pedido', verbose_name='pedido'),
        ),
        migrations.AlterField(
            model_name='historicalitempedido',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='peso'),
        ),
        migrations.AlterField(
            model_name='historicalitempedido',
            name='produto',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='loja.produto', verbose_name='produto'),
        ),
        migrations.AlterField(
            model_name='historicalitempedido',
            name='quantidade',
            field=models.IntegerField(default=1, verbose_name='quantidade'),
        ),
        migrations.AlterField(
            model_name='historicalitempedido',
            name='requer_entrega',
            field=models.BooleanField(default=True, verbose_name='requer entrega'),
        ),
        migrations.AlterField(
            model_name='historicalitempedido',
            name='sku',
            field=models.CharField(blank=True, max_length=100, verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='historicalitempedido',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='alterado por'),
        ),
        migrations.AlterField(
            model_name='historicalitempedido',
            name='variante',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='loja.varianteproduto', verbose_name='variante'),
        ),
        migrations.AlterField(
            model_name='historicalmidiaproduto',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por'),
        ),
        migrations.AlterField(
            model_name='historicalmidiaproduto',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='alterado por'),
        ),
        migrations.AlterField(
            model_name='historicalmidiaproduto',
            name='url',
            field=models.URLField(max_length=500, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='historicalpagamentopedido',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='valor'),
        ),
        migrations.AlterField(
            model_name='historicalpagamentopedido',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por'),
        ),
        migrations.AlterField(
            model_name='historicalpagamentopedido',
            name='currency',
            field=models.CharField(default='BRL', max_length=3, verbose_name='moeda'),
        ),
        migrations.AlterField(
            model_name='historicalpagamentopedido',
            name='installments',
            field=models.PositiveIntegerField(default=1, verbose_name='parcelas'),
        ),
        migrations.AlterField(
            model_name='historicalpagamentopedido',
            name='metadata',
            field=apps.loja.models.base.JSONDecimalField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='dados extras'),
        ),
        migrations.AlterField(
            model_name='historicalpagamentopedido',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='pago em'),
        ),
        migrations.AlterField(
            model_name='historicalpagamentopedido',
            name='pedido',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='loja.pedido', verbose_name='pedido'),
        ),
        migrations.AlterField(
            model_name='historicalpagamentopedido',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('authorized', 'Autorizado'), ('paid', 'Pago'), ('refunded', 'Reembolsado'), ('voided', 'Estornado'), ('failed', 'Falhou')], default='pending', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='historicalpagamentopedido',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='id da transacao'),
        ),
        migrations.AlterField(
            model_name='historicalpagamentopedido',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='alterado por'),
        ),
        migrations.AlterField(
            model_name='historicalpedido',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='cancelado em'),
        ),
        migrations.AlterField(
            model_name='historicalpedido',
            name='chave',
            field=models.CharField(db_index=True, default=apps.loja.models.pedido.nova_chave_pedido, max_length=40, verbose_name='chave do pedido'),
        ),
        migrations.AlterField(
            model_name='historicalpedido',
            name='cliente',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='loja.cliente', verbose_name='cliente'),
        ),
        migrations.AlterField(
            model_name='historicalpedido',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por'),
        ),
        migrations.AlterField(
            model_name='historicalpedido',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='historicalpedido',
            name='endereco_cobranca',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.address', verbose_name='endereco de cobranca'),
        ),
        migrations.AlterField(
            model_name='historicalpedido',
            name='endereco_entrega',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.address', verbose_name='endereco de entrega'),
        ),
        migrations.AlterField(
            model_name='historicalpedido',
            name='financial_status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('authorized', 'Autorizado'), ('paid', 'Pago'), ('partially_paid', 'Parcialmente pago'), ('refunded', 'Reembolsado'), ('partially_refunded', 'Reembolso parcial'), ('voided', 'Estornado'), ('failed', 'Falhou')], default='pending', max_length=30, verbose_name='situacao do pagamento'),
        ),
        migrations.AlterField(
            model_name='historicalpedido',
            name='forma_pagamento',
            field=models.CharField(blank=True, max_length=100, verbose_name='forma de pagamento'),
        ),
        migrations.AlterField(
            model_name='historicalpedido',
            name='forma_pagamento_titulo',
            field=models.CharField(blank=True, max_length=200, verbose_name='nome da forma de pagamento'),
        ),
        migrations.AlterField(
            model_name='historicalpedido',
            name='fulfilled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='concluido em'),
        ),
        migrations.AlterField(
            model_name='historicalpedido',
            name='fulfillment_status',
            field=models.CharField(choices=[('unfulfilled', 'Nao atendido'), ('partial', 'Parcial'), ('fulfilled', 'Atendido'), ('returned', 'Devolvido')], default='unfulfilled', max_length=20, verbose_name='situacao da entrega'),
        ),
        migrations.AlterField(
            model_name='historicalpedido',
            name='hash_carrinho',
            field=models.CharField(blank=True, max_length=64, verbose_name='hash do carrinho'),
        ),
        migrations.AlterField(
            model_name='historicalpedido',
            name='id_pai',
            field=models.PositiveBigIntegerField(default=0, verbose_name='pedido pai (id)'),
        ),
        migrations.AlterField(
            model_name='historicalpedido',
            name='ip_cliente',
            field=models.CharField(blank=True, max_length=64, verbose_name='IP do cliente'),
        ),
        migrations.AlterField(
            model_name='historicalpedido',
            name='linhas_cupom',
            field=apps.loja.models.base.JSONDecimalField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='cupons aplicados'),
        ),
        migrations.AlterField(
            model_name='historicalpedido',
            name='linhas_frete',
            field=apps.loja.models.base.JSONDecimalField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='fretes'),
        ),
        migrations.AlterField(
            model_name='historicalpedido',
            name='linhas_imposto',
            field=apps.loja.models.base.JSONDecimalField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='impostos'),
        ),
        migrations.AlterField(
            model_name='historicalpedido',
            name='linhas_taxa',
            field=apps.loja.models.base.JSONDecimalField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='taxas'),
        ),
        migrations.AlterField(
            model_name='historicalpedido',
            name='moeda',
            field=models.CharField(default='BRL', max_length=3, verbose_name='moeda'),
        ),
        migrations.AlterField(
            model_name='historicalpedido',
            name='notas',
            field=models.TextField(blank=True, verbose_name='notas'),
        ),
        migrations.AlterField(
            model_name='historicalpedido',
            name='observacao_cliente',
            field=models.TextField(blank=True, verbose_name='observacao do cliente'),
        ),
        migrations.AlterField(
            model_name='historicalpedido',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='pago em'),
        ),
        migrations.AlterField(
            model_name='historicalpedido',
            name='placed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='data do pedido'),
        ),
        migrations.AlterField(
            model_name='historicalpedido',
            name='preco_inclui_imposto',
            field=models.BooleanField(default=False, verbose_name='preco inclui imposto'),
        ),
        migrations.AlterField(
            model_name='historicalpedido',
            name='reembolsos',
            field=apps.loja.models.base.JSONDecimalField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='reembolsos'),
        ),
        migrations.AlterField(
            model_name='historicalpedido',
            name='shipping_method',
            field=models.CharField(blank=True, max_length=150, verbose_name='metodo de envio'),
        ),
        migrations.AlterField(
            model_name='historicalpedido',
            name='source_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='canal de origem'),
        ),
        migrations.AlterField(
            model_name='historicalpedido',
            name='source_reference',
            field=models.CharField(blank=True, max_length=255, verbose_name='referencia na origem'),
        ),
        migrations.AlterField(
            model_name='historicalpedido',
            name='status',
            field=models.CharField(choices=[('checkout-draft', 'Rascunho'), ('pending', 'Pendente'), ('confirmed', 'Confirmado'), ('processing', 'Processando'), ('on-hold', 'Aguardando'), ('completed', 'Concluido'), ('cancelled', 'Cancelado'), ('refunded', 'Reembolsado'), ('failed', 'Falhou'), ('archived', 'Arquivado'), ('trash', 'Lixeira')], db_index=True, default='pending', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='historicalpedido',
            name='telefone',
            field=models.CharField(blank=True, max_length=30, verbose_name='telefone'),
        ),
        migrations.AlterField(
            model_name='historicalpedido',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='alterado por'),
        ),
        migrations.AlterField(
            model_name='historicalpedido',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255, verbose_name='navegador do cliente'),
        ),
        migrations.AlterField(
            model_name='historicalpedido',
            name='versao',
            field=models.CharField(default='9.0.0', max_length=20, verbose_name='versao'),
        ),
        migrations.AlterField(
            model_name='historicalproduto',
            name='atributos',
            field=apps.loja.models.base.JSONDecimalField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='atributos'),
        ),
        migrations.AlterField(
            model_name='historicalproduto',
            name='avaliacoes_permitidas',
            field=models.BooleanField(default=True, verbose_name='permite avaliacoes'),
        ),
        migrations.AlterField(
            model_name='historicalproduto',
            name='categoria',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='loja.categoria', verbose_name='categoria principal'),
        ),
        migrations.AlterField(
            model_name='historicalproduto',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por'),
        ),
        migrations.AlterField(
            model_name='historicalproduto',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='descricao'),
        ),
        migrations.AlterField(
            model_name='historicalproduto',
            name='descricao_curta',
            field=models.TextField(blank=True, verbose_name='descricao curta'),
        ),
        migrations.AlterField(
            model_name='historicalproduto',
            name='destaque',
            field=models.BooleanField(default=False, verbose_name='destaque'),
        ),
        migrations.AlterField(
            model_name='historicalproduto',
            name='fornecedor',
            field=models.CharField(blank=True, max_length=150, verbose_name='fornecedor'),
        ),
        migrations.AlterField(
            model_name='historicalproduto',
            name='id_pai',
            field=models.PositiveBigIntegerField(default=0, verbose_name='produto pai (id)'),
        ),
        migrations.AlterField(
            model_name='historicalproduto',
            name='marca',
            field=models.CharField(blank=True, max_length=150, verbose_name='marca'),
        ),
        migrations.AlterField(
            model_name='historicalproduto',
            name='nota_compra',
            field=models.TextField(blank=True, verbose_name='nota da compra'),
        ),
        migrations.AlterField(
            model_name='historicalproduto',
            name='ordem_menu',
            field=models.IntegerField(default=0, verbose_name='ordem no menu'),
        ),
        migrations.AlterField(
            model_name='historicalproduto',
            name='publicado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='publicado em'),
        ),
        migrations.AlterField(
            model_name='historicalproduto',
            name='seo_descricao',
            field=models.TextField(blank=True, verbose_name='descricao SEO'),
        ),
        migrations.AlterField(
            model_name='historicalproduto',
            name='seo_titulo',
            field=models.CharField(blank=True, max_length=255, verbose_name='titulo SEO'),
        ),
        migrations.AlterField(
            model_name='historicalproduto',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=255, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='historicalproduto',
            name='status',
            field=models.CharField(choices=[('publish', 'Publicado'), ('draft', 'Rascunho'), ('pending', 'Pendente'), ('private', 'Privado'), ('archived', 'Arquivado'), ('trash', 'Lixeira')], default='publish', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='historicalproduto',
            name='texto_botao',
            field=models.CharField(blank=True, max_length=100, verbose_name='texto do botao'),
        ),
        migrations.AlterField(
            model_name='historicalproduto',
            name='tipo',
            field=models.CharField(choices=[('simple', 'Simples'), ('variable', 'Variavel'), ('bundle', 'Bundle'), ('grouped', 'Agrupado'), ('external', 'Externo')], default='simple', max_length=20, verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='historicalproduto',
            name='total_vendas',
            field=models.PositiveIntegerField(default=0, verbose_name='total de vendas'),
        ),
        migrations.AlterField(
            model_name='historicalproduto',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='alterado por'),
        ),
        migrations.AlterField(
            model_name='historicalproduto',
            name='url_externa',
            field=models.URLField(blank=True, verbose_name='URL externa'),
        ),
        migrations.AlterField(
            model_name='historicalproduto',
            name='visibilidade',
            field=models.CharField(choices=[('visible', 'Loja e busca'), ('catalog', 'Somente loja'), ('search', 'Somente busca'), ('hidden', 'Oculto')], default='visible', max_length=20, verbose_name='visibilidade'),
        ),
        migrations.AlterField(
            model_name='historicaltag',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por'),
        ),
        migrations.AlterField(
            model_name='historicaltag',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='alterado por'),
        ),
        migrations.AlterField(
            model_name='historicaltipovariante',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por'),
        ),
        migrations.AlterField(
            model_name='historicaltipovariante',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='historicaltipovariante',
            name='posicao',
            field=models.PositiveIntegerField(default=0, verbose_name='posicao'),
        ),
        migrations.AlterField(
            model_name='historicaltipovariante',
            name='produto',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='loja.produto', verbose_name='produto'),
        ),
        migrations.AlterField(
            model_name='historicaltipovariante',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='alterado por'),
        ),
        migrations.AlterField(
            model_name='historicalvalordavarianteproduto',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por'),
        ),
        migrations.AlterField(
            model_name='historicalvalordavarianteproduto',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='alterado por'),
        ),
        migrations.AlterField(
            model_name='historicalvalordavarianteproduto',
            name='valor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='loja.valorvariante', verbose_name='valor'),
        ),
        migrations.AlterField(
            model_name='historicalvalordavarianteproduto',
            name='variante',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='loja.varianteproduto', verbose_name='variante'),
        ),
        migrations.AlterField(
            model_name='historicalvalorvariante',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por'),
        ),
        migrations.AlterField(
            model_name='historicalvalorvariante',
            name='posicao',
            field=models.PositiveIntegerField(default=0, verbose_name='posicao'),
        ),
        migrations.AlterField(
            model_name='historicalvalorvariante',
            name='tipo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='loja.tipovariante', verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='historicalvalorvariante',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='alterado por'),
        ),
        migrations.AlterField(
            model_name='historicalvalorvariante',
            name='valor',
            field=models.CharField(max_length=100, verbose_name='valor'),
        ),
        migrations.AlterField(
            model_name='historicalvarianteproduto',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='codigo de barras'),
        ),
        migrations.AlterField(
            model_name='historicalvarianteproduto',
            name='compare_at_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='preco de comparacao'),
        ),
        migrations.AlterField(
            model_name='historicalvarianteproduto',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por'),
        ),
        migrations.AlterField(
            model_name='historicalvarianteproduto',
            name='dimensions',
            field=apps.loja.models.base.JSONDecimalField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='dimensoes'),
        ),
        migrations.AlterField(
            model_name='historicalvarianteproduto',
            name='downloadable',
            field=models.BooleanField(default=False, verbose_name='para download'),
        ),
        migrations.AlterField(
            model_name='historicalvarianteproduto',
            name='inventory_policy',
            field=models.CharField(choices=[('deny', 'Nao vender sem estoque'), ('continue', 'Continuar vendendo')], default='deny', max_length=10, verbose_name='quando acabar o estoque'),
        ),
        migrations.AlterField(
            model_name='historicalvarianteproduto',
            name='inventory_quantity',
            field=models.IntegerField(default=0, verbose_name='estoque'),
        ),
        migrations.AlterField(
            model_name='historicalvarianteproduto',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='variante padrao'),
        ),
        migrations.AlterField(
            model_name='historicalvarianteproduto',
            name='low_stock_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='estoque minimo'),
        ),
        migrations.AlterField(
            model_name='historicalvarianteproduto',
            name='manage_inventory',
            field=models.BooleanField(default=True, verbose_name='controlar estoque'),
        ),
        migrations.AlterField(
            model_name='historicalvarianteproduto',
            name='posicao',
            field=models.PositiveIntegerField(default=0, verbose_name='posicao'),
        ),
        migrations.AlterField(
            model_name='historicalvarianteproduto',
            name='produto',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='loja.produto', verbose_name='produto'),
        ),
        migrations.AlterField(
            model_name='historicalvarianteproduto',
            name='requires_shipping',
            field=models.BooleanField(default=True, verbose_name='requer entrega'),
        ),
        migrations.AlterField(
            model_name='historicalvarianteproduto',
            name='sale_ends_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fim da promocao'),
        ),
        migrations.AlterField(
            model_name='historicalvarianteproduto',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='preco promocional'),
        ),
        migrations.AlterField(
            model_name='historicalvarianteproduto',
            name='sale_starts_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='inicio da promocao'),
        ),
        migrations.AlterField(
            model_name='historicalvarianteproduto',
            name='shipping_class',
            field=models.CharField(blank=True, max_length=100, verbose_name='classe de entrega'),
        ),
        migrations.AlterField(
            model_name='historicalvarianteproduto',
            name='sku',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='historicalvarianteproduto',
            name='sold_individually',
            field=models.BooleanField(default=False, verbose_name='vendido individualmente'),
        ),
        migrations.AlterField(
            model_name='historicalvarianteproduto',
            name='stock_status',
            field=models.CharField(choices=[('instock', 'Em estoque'), ('outofstock', 'Sem estoque'), ('onbackorder', 'Sob encomenda')], default='instock', max_length=20, verbose_name='situacao do estoque'),
        ),
        migrations.AlterField(
            model_name='historicalvarianteproduto',
            name='tax_class',
            field=models.CharField(blank=True, max_length=100, verbose_name='classe fiscal'),
        ),
        migrations.AlterField(
            model_name='historicalvarianteproduto',
            name='tax_status',
            field=models.CharField(choices=[('taxable', 'Tributavel'), ('shipping', 'Somente o frete'), ('none', 'Nao tributavel')], default='taxable', max_length=20, verbose_name='situacao fiscal'),
        ),
        migrations.AlterField(
            model_name='historicalvarianteproduto',
            name='taxable',
            field=models.BooleanField(default=True, verbose_name='tributavel'),
        ),
        migrations.AlterField(
            model_name='historicalvarianteproduto',
            name='titulo',
            field=models.CharField(default='Default', max_length=255, verbose_name='titulo'),
        ),
        migrations.AlterField(
            model_name='historicalvarianteproduto',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='alterado por'),
        ),
        migrations.AlterField(
            model_name='historicalvarianteproduto',
            name='virtual',
            field=models.BooleanField(default=False, verbose_name='virtual'),
        ),
        migrations.AlterField(
            model_name='historicalvarianteproduto',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='peso'),
        ),
        migrations.AlterField(
            model_name='historicalvarianteproduto',
            name='weight_unit',
            field=models.CharField(default='kg', max_length=5, verbose_name='unidade de peso'),
        ),
        migrations.AlterField(
            model_name='itembundle',
            name='bundle_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='loja.produto', verbose_name='produto bundle'),
        ),
        migrations.AlterField(
            model_name='itembundle',
            name='component_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bundles', to='loja.varianteproduto', verbose_name='componente'),
        ),
        migrations.AlterField(
            model_name='itembundle',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='criado por'),
        ),
        migrations.AlterField(
            model_name='itembundle',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='quantidade'),
        ),
        migrations.AlterField(
            model_name='itembundle',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='alterado por'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='classe_fiscal',
            field=models.CharField(blank=True, max_length=100, verbose_name='classe fiscal'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='criado por'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='id_variacao',
            field=models.PositiveBigIntegerField(default=0, verbose_name='id da variacao'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='impostos',
            field=apps.loja.models.base.JSONDecimalField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='impostos'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='nome',
            field=models.CharField(blank=True, max_length=255, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='loja.pedido', verbose_name='pedido'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='peso'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_pedido', to='loja.produto', verbose_name='produto'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='quantidade',
            field=models.IntegerField(default=1, verbose_name='quantidade'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='requer_entrega',
            field=models.BooleanField(default=True, verbose_name='requer entrega'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='sku',
            field=models.CharField(blank=True, max_length=100, verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='alterado por'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='variante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_pedido', to='loja.varianteproduto', verbose_name='variante'),
        ),
        migrations.AlterField(
            model_name='midiaproduto',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='criado por'),
        ),
        migrations.AlterField(
            model_name='midiaproduto',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='alterado por'),
        ),
        migrations.AlterField(
            model_name='midiaproduto',
            name='url',
            field=models.URLField(max_length=500, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='pagamentopedido',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='valor'),
        ),
        migrations.AlterField(
            model_name='pagamentopedido',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='criado por'),
        ),
        migrations.AlterField(
            model_name='pagamentopedido',
            name='currency',
            field=models.CharField(default='BRL', max_length=3, verbose_name='moeda'),
        ),
        migrations.AlterField(
            model_name='pagamentopedido',
            name='installments',
            field=models.PositiveIntegerField(default=1, verbose_name='parcelas'),
        ),
        migrations.AlterField(
            model_name='pagamentopedido',
            name='metadata',
            field=apps.loja.models.base.JSONDecimalField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='dados extras'),
        ),
        migrations.AlterField(
            model_name='pagamentopedido',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='pago em'),
        ),
        migrations.AlterField(
            model_name='pagamentopedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='loja.pedido', verbose_name='pedido'),
        ),
        migrations.AlterField(
            model_name='pagamentopedido',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('authorized', 'Autorizado'), ('paid', 'Pago'), ('refunded', 'Reembolsado'), ('voided', 'Estornado'), ('failed', 'Falhou')], default='pending', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='pagamentopedido',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='id da transacao'),
        ),
        migrations.AlterField(
            model_name='pagamentopedido',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='alterado por'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='cancelado em'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='chave',
            field=models.CharField(default=apps.loja.models.pedido.nova_chave_pedido, max_length=40, unique=True, verbose_name='chave do pedido'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='loja.cliente', verbose_name='cliente'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='criado por'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='endereco_cobranca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_cobranca', to='core.address', verbose_name='endereco de cobranca'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='endereco_entrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_entrega', to='core.address', verbose_name='endereco de entrega'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='financial_status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('authorized', 'Autorizado'), ('paid', 'Pago'), ('partially_paid', 'Parcialmente pago'), ('refunded', 'Reembolsado'), ('partially_refunded', 'Reembolso parcial'), ('voided', 'Estornado'), ('failed', 'Falhou')], default='pending', max_length=30, verbose_name='situacao do pagamento'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='forma_pagamento',
            field=models.CharField(blank=True, max_length=100, verbose_name='forma de pagamento'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='forma_pagamento_titulo',
            field=models.CharField(blank=True, max_length=200, verbose_name='nome da forma de pagamento'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fulfilled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='concluido em'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fulfillment_status',
            field=models.CharField(choices=[('unfulfilled', 'Nao atendido'), ('partial', 'Parcial'), ('fulfilled', 'Atendido'), ('returned', 'Devolvido')], default='unfulfilled', max_length=20, verbose_name='situacao da entrega'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='hash_carrinho',
            field=models.CharField(blank=True, max_length=64, verbose_name='hash do carrinho'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='id_pai',
            field=models.PositiveBigIntegerField(default=0, verbose_name='pedido pai (id)'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='ip_cliente',
            field=models.CharField(blank=True, max_length=64, verbose_name='IP do cliente'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='linhas_cupom',
            field=apps.loja.models.base.JSONDecimalField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='cupons aplicados'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='linhas_frete',
            field=apps.loja.models.base.JSONDecimalField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='fretes'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='linhas_imposto',
            field=apps.loja.models.base.JSONDecimalField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='impostos'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='linhas_taxa',
            field=apps.loja.models.base.JSONDecimalField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='taxas'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='moeda',
            field=models.CharField(default='BRL', max_length=3, verbose_name='moeda'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='notas',
            field=models.TextField(blank=True, verbose_name='notas'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='observacao_cliente',
            field=models.TextField(blank=True, verbose_name='observacao do cliente'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='pago em'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='placed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='data do pedido'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='preco_inclui_imposto',
            field=models.BooleanField(default=False, verbose_name='preco inclui imposto'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='reembolsos',
            field=apps.loja.models.base.JSONDecimalField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='reembolsos'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='shipping_method',
            field=models.CharField(blank=True, max_length=150, verbose_name='metodo de envio'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='source_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='canal de origem'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='source_reference',
            field=models.CharField(blank=True, max_length=255, verbose_name='referencia na origem'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('checkout-draft', 'Rascunho'), ('pending', 'Pendente'), ('confirmed', 'Confirmado'), ('processing', 'Processando'), ('on-hold', 'Aguardando'), ('completed', 'Concluido'), ('cancelled', 'Cancelado'), ('refunded', 'Reembolsado'), ('failed', 'Falhou'), ('archived', 'Arquivado'), ('trash', 'Lixeira')], db_index=True, default='pending', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='telefone',
            field=models.CharField(blank=True, max_length=30, verbose_name='telefone'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='alterado por'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255, verbose_name='navegador do cliente'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='versao',
            field=models.CharField(default='9.0.0', max_length=20, verbose_name='versao'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='atributos',
            field=apps.loja.models.base.JSONDecimalField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='atributos'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='avaliacoes_permitidas',
            field=models.BooleanField(default=True, verbose_name='permite avaliacoes'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produtos_principais', to='loja.categoria', verbose_name='categoria principal'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='categorias',
            field=models.ManyToManyField(blank=True, related_name='produtos', to='loja.categoria', verbose_name='categorias'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='criado por'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='descricao'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao_curta',
            field=models.TextField(blank=True, verbose_name='descricao curta'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='destaque',
            field=models.BooleanField(default=False, verbose_name='destaque'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='fornecedor',
            field=models.CharField(blank=True, max_length=150, verbose_name='fornecedor'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='id_pai',
            field=models.PositiveBigIntegerField(default=0, verbose_name='produto pai (id)'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='marca',
            field=models.CharField(blank=True, max_length=150, verbose_name='marca'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nota_compra',
            field=models.TextField(blank=True, verbose_name='nota da compra'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='ordem_menu',
            field=models.IntegerField(default=0, verbose_name='ordem no menu'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='publicado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='publicado em'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='seo_descricao',
            field=models.TextField(blank=True, verbose_name='descricao SEO'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='seo_titulo',
            field=models.CharField(blank=True, max_length=255, verbose_name='titulo SEO'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=255, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='status',
            field=models.CharField(choices=[('publish', 'Publicado'), ('draft', 'Rascunho'), ('pending', 'Pendente'), ('private', 'Privado'), ('archived', 'Arquivado'), ('trash', 'Lixeira')], default='publish', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='produtos', to='loja.tag', verbose_name='tags'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='texto_botao',
            field=models.CharField(blank=True, max_length=100, verbose_name='texto do botao'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='tipo',
            field=models.CharField(choices=[('simple', 'Simples'), ('variable', 'Variavel'), ('bundle', 'Bundle'), ('grouped', 'Agrupado'), ('external', 'Externo')], default='simple', max_length=20, verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='total_vendas',
            field=models.PositiveIntegerField(default=0, verbose_name='total de vendas'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='alterado por'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='url_externa',
            field=models.URLField(blank=True, verbose_name='URL externa'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='visibilidade',
            field=models.CharField(choices=[('visible', 'Loja e busca'), ('catalog', 'Somente loja'), ('search', 'Somente busca'), ('hidden', 'Oculto')], default='visible', max_length=20, verbose_name='visibilidade'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='criado por'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='alterado por'),
        ),
        migrations.AlterField(
            model_name='tipovariante',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='criado por'),
        ),
        migrations.AlterField(
            model_name='tipovariante',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='tipovariante',
            name='posicao',
            field=models.PositiveIntegerField(default=0, verbose_name='posicao'),
        ),
        migrations.AlterField(
            model_name='tipovariante',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_variante', to='loja.produto', verbose_name='produto'),
        ),
        migrations.AlterField(
            model_name='tipovariante',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='alterado por'),
        ),
        migrations.AlterField(
            model_name='valordavarianteproduto',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='criado por'),
        ),
        migrations.AlterField(
            model_name='valordavarianteproduto',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='alterado por'),
        ),
        migrations.AlterField(
            model_name='valordavarianteproduto',
            name='valor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='loja.valorvariante', verbose_name='valor'),
        ),
        migrations.AlterField(
            model_name='valordavarianteproduto',
            name='variante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opcoes', to='loja.varianteproduto', verbose_name='variante'),
        ),
        migrations.AlterField(
            model_name='valorvariante',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='criado por'),
        ),
        migrations.AlterField(
            model_name='valorvariante',
            name='posicao',
            field=models.PositiveIntegerField(default=0, verbose_name='posicao'),
        ),
        migrations.AlterField(
            model_name='valorvariante',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='loja.tipovariante', verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='valorvariante',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='alterado por'),
        ),
        migrations.AlterField(
            model_name='valorvariante',
            name='valor',
            field=models.CharField(max_length=100, verbose_name='valor'),
        ),
        migrations.AlterField(
            model_name='varianteproduto',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='codigo de barras'),
        ),
        migrations.AlterField(
            model_name='varianteproduto',
            name='compare_at_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='preco de comparacao'),
        ),
        migrations.AlterField(
            model_name='varianteproduto',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='criado por'),
        ),
        migrations.AlterField(
            model_name='varianteproduto',
            name='dimensions',
            field=apps.loja.models.base.JSONDecimalField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='dimensoes'),
        ),
        migrations.AlterField(
            model_name='varianteproduto',
            name='downloadable',
            field=models.BooleanField(default=False, verbose_name='para download'),
        ),
        migrations.AlterField(
            model_name='varianteproduto',
            name='inventory_policy',
            field=models.CharField(choices=[('deny', 'Nao vender sem estoque'), ('continue', 'Continuar vendendo')], default='deny', max_length=10, verbose_name='quando acabar o estoque'),
        ),
        migrations.AlterField(
            model_name='varianteproduto',
            name='inventory_quantity',
            field=models.IntegerField(default=0, verbose_name='estoque'),
        ),
        migrations.AlterField(
            model_name='varianteproduto',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='variante padrao'),
        ),
        migrations.AlterField(
            model_name='varianteproduto',
            name='low_stock_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='estoque minimo'),
        ),
        migrations.AlterField(
            model_name='varianteproduto',
            name='manage_inventory',
            field=models.BooleanField(default=True, verbose_name='controlar estoque'),
        ),
        migrations.AlterField(
            model_name='varianteproduto',
            name='posicao',
            field=models.PositiveIntegerField(default=0, verbose_name='posicao'),
        ),
        migrations.AlterField(
            model_name='varianteproduto',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='loja.produto', verbose_name='produto'),
        ),
        migrations.AlterField(
            model_name='varianteproduto',
            name='requires_shipping',
            field=models.BooleanField(default=True, verbose_name='requer entrega'),
        ),
        migrations.AlterField(
            model_name='varianteproduto',
            name='sale_ends_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fim da promocao'),
        ),
        migrations.AlterField(
            model_name='varianteproduto',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='preco promocional'),
        ),
        migrations.AlterField(
            model_name='varianteproduto',
            name='sale_starts_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='inicio da promocao'),
        ),
        migrations.AlterField(
            model_name='varianteproduto',
            name='shipping_class',
            field=models.CharField(blank=True, max_length=100, verbose_name='classe de entrega'),
        ),
        migrations.AlterField(
            model_name='varianteproduto',
            name='sku',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='varianteproduto',
            name='sold_individually',
            field=models.BooleanField(default=False, verbose_name='vendido individualmente'),
        ),
        migrations.AlterField(
            model_name='varianteproduto',
            name='stock_status',
            field=models.CharField(choices=[('instock', 'Em estoque'), ('outofstock', 'Sem estoque'), ('onbackorder', 'Sob encomenda')], default='instock', max_length=20, verbose_name='situacao do estoque'),
        ),
        migrations.AlterField(
            model_name='varianteproduto',
            name='tax_class',
            field=models.CharField(blank=True, max_length=100, verbose_name='classe fiscal'),
        ),
        migrations.AlterField(
            model_name='varianteproduto',
            name='tax_status',
            field=models.CharField(choices=[('taxable', 'Tributavel'), ('shipping', 'Somente o frete'), ('none', 'Nao tributavel')], default='taxable', max_length=20, verbose_name='situacao fiscal'),
        ),
        migrations.AlterField(
            model_name='varianteproduto',
            name='taxable',
            field=models.BooleanField(default=True, verbose_name='tributavel'),
        ),
        migrations.AlterField(
            model_name='varianteproduto',
            name='titulo',
            field=models.CharField(default='Default', max_length=255, verbose_name='titulo'),
        ),
        migrations.AlterField(
            model_name='varianteproduto',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='alterado por'),
        ),
        migrations.AlterField(
            model_name='varianteproduto',
            name='valores',
            field=models.ManyToManyField(blank=True, through='loja.ValorDaVarianteProduto', to='loja.valorvariante', verbose_name='valores'),
        ),
        migrations.AlterField(
            model_name='varianteproduto',
            name='virtual',
            field=models.BooleanField(default=False, verbose_name='virtual'),
        ),
        migrations.AlterField(
            model_name='varianteproduto',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='peso'),
        ),
        migrations.AlterField(
            model_name='varianteproduto',
            name='weight_unit',
            field=models.CharField(default='kg', max_length=5, verbose_name='unidade de peso'),
        ),
    ]
