# Generated by Django 5.1.15 on 2026-09-28 12:43

import apps.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_rotulos_ptbr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupom',
            name='minimum_subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='subtotal minimo'),
        ),
        migrations.AlterField(
            model_name='cupom',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='valor'),
        ),
        migrations.AlterField(
            model_name='historicalcupom',
            name='minimum_subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='subtotal minimo'),
        ),
        migrations.AlterField(
            model_name='historicalcupom',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='valor'),
        ),
        migrations.AlterField(
            model_name='historicalitempedido',
            name='imposto_subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='imposto do subtotal'),
        ),
        migrations.AlterField(
            model_name='historicalitempedido',
            name='imposto_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='imposto total'),
        ),
        migrations.AlterField(
            model_name='historicalitempedido',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='preco unitario'),
        ),
        migrations.AlterField(
            model_name='historicalitempedido',
            name='quantidade',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='quantidade'),
        ),
        migrations.AlterField(
            model_name='historicalitempedido',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='subtotal'),
        ),
        migrations.AlterField(
            model_name='historicalitempedido',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='total'),
        ),
        migrations.AlterField(
            model_name='historicalitempedido',
            name='total_desconto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='desconto'),
        ),
        migrations.AlterField(
            model_name='historicalpagamentopedido',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='valor'),
        ),
        migrations.AlterField(
            model_name='historicalpagamentopedido',
            name='installments',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='parcelas'),
        ),
        migrations.AlterField(
            model_name='historicalpedido',
            name='imposto_carrinho',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='imposto dos itens'),
        ),
        migrations.AlterField(
            model_name='historicalpedido',
            name='imposto_desconto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='imposto do desconto'),
        ),
        migrations.AlterField(
            model_name='historicalpedido',
            name='imposto_frete',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='imposto do frete'),
        ),
        migrations.AlterField(
            model_name='historicalpedido',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='subtotal'),
        ),
        migrations.AlterField(
            model_name='historicalpedido',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='total'),
        ),
        migrations.AlterField(
            model_name='historicalpedido',
            name='total_desconto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='total de desconto'),
        ),
        migrations.AlterField(
            model_name='historicalpedido',
            name='total_frete',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='total de frete'),
        ),
        migrations.AlterField(
            model_name='historicalpedido',
            name='total_impostos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='total de impostos'),
        ),
        migrations.AlterField(
            model_name='historicalpedido',
            name='total_reembolsado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='total reembolsado'),
        ),
        migrations.AlterField(
            model_name='historicalvarianteproduto',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, max_length=100, validators=[apps.core.validators.validar_gtin], verbose_name='codigo de barras'),
        ),
        migrations.AlterField(
            model_name='historicalvarianteproduto',
            name='compare_at_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='preco de comparacao'),
        ),
        migrations.AlterField(
            model_name='historicalvarianteproduto',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='custo'),
        ),
        migrations.AlterField(
            model_name='historicalvarianteproduto',
            name='low_stock_amount',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='estoque minimo'),
        ),
        migrations.AlterField(
            model_name='historicalvarianteproduto',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='preco'),
        ),
        migrations.AlterField(
            model_name='historicalvarianteproduto',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='preco promocional'),
        ),
        migrations.AlterField(
            model_name='historicalvarianteproduto',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='peso'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='imposto_subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='imposto do subtotal'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='imposto_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='imposto total'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='preco unitario'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='quantidade',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='quantidade'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='subtotal'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='total'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='total_desconto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='desconto'),
        ),
        migrations.AlterField(
            model_name='pagamentopedido',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='valor'),
        ),
        migrations.AlterField(
            model_name='pagamentopedido',
            name='installments',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='parcelas'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='imposto_carrinho',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='imposto dos itens'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='imposto_desconto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='imposto do desconto'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='imposto_frete',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='imposto do frete'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='subtotal'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='total'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='total_desconto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='total de desconto'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='total_frete',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='total de frete'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='total_impostos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='total de impostos'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='total_reembolsado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='total reembolsado'),
        ),
        migrations.AlterField(
            model_name='varianteproduto',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, max_length=100, validators=[apps.core.validators.validar_gtin], verbose_name='codigo de barras'),
        ),
        migrations.AlterField(
            model_name='varianteproduto',
            name='compare_at_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='preco de comparacao'),
        ),
        migrations.AlterField(
            model_name='varianteproduto',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='custo'),
        ),
        migrations.AlterField(
            model_name='varianteproduto',
            name='low_stock_amount',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='estoque minimo'),
        ),
        migrations.AlterField(
            model_name='varianteproduto',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='preco'),
        ),
        migrations.AlterField(
            model_name='varianteproduto',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='preco promocional'),
        ),
        migrations.AlterField(
            model_name='varianteproduto',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='peso'),
        ),
    ]
