# Generated by Django 5.1.15 on 2026-09-28 15:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rotulos_ptbr'),
        ('loja', '0003_validadores'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tipovariante',
            name='tipo_variante_produto_nome',
        ),
        migrations.RemoveField(
            model_name='historicaltipovariante',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='tipovariante',
            name='produto',
        ),
        migrations.AddField(
            model_name='produto',
            name='opcoes_variante',
            field=models.ManyToManyField(blank=True, help_text='Valores que este produto usa (ex.: Cor: Preto, Tamanho: M). Ao salvar um produto variavel, as combinacoes viram variantes.', related_name='produtos', to='loja.valorvariante', verbose_name='opcoes de variante'),
        ),
        migrations.AddConstraint(
            model_name='tipovariante',
            constraint=models.UniqueConstraint(fields=('account', 'nome'), name='tipo_variante_nome_conta'),
        ),
    ]
