# Generated by Django 5.1.15 on 2026-09-28 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_tipos_variante_globais'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='opcoes_variante',
        ),
    ]
