# Generated by Django 5.1.15 on 2026-09-29 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0005_remove_opcoes_variante'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupom',
            name='categorias_excluidas',
            field=models.ManyToManyField(blank=True, related_name='cupons_que_excluem', to='loja.categoria', verbose_name='categorias excluidas'),
        ),
        migrations.AddField(
            model_name='cupom',
            name='excluir_promocao',
            field=models.BooleanField(default=False, help_text='Item com preco promocional ativo fica fora do desconto.', verbose_name='nao vale para itens em promocao'),
        ),
        migrations.AddField(
            model_name='cupom',
            name='produtos_excluidos',
            field=models.ManyToManyField(blank=True, related_name='cupons_que_excluem', to='loja.produto', verbose_name='produtos excluidos'),
        ),
        migrations.AddField(
            model_name='historicalcupom',
            name='excluir_promocao',
            field=models.BooleanField(default=False, help_text='Item com preco promocional ativo fica fora do desconto.', verbose_name='nao vale para itens em promocao'),
        ),
    ]
