# Generated by Django 5.1.15 on 2026-09-30 12:43

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0006_cupom_exclusoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduto',
            name='descricao',
            field=apps.core.fields.TextoHTMLField(blank=True, verbose_name='descricao'),
        ),
        migrations.AlterField(
            model_name='historicalproduto',
            name='descricao_curta',
            field=apps.core.fields.TextoHTMLField(blank=True, verbose_name='descricao curta'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=apps.core.fields.TextoHTMLField(blank=True, verbose_name='descricao'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao_curta',
            field=apps.core.fields.TextoHTMLField(blank=True, verbose_name='descricao curta'),
        ),
    ]
