# Generated by Django 5.1.15 on 2026-09-30 16:01

import apps.loja.models.cupom
from django.conf import settings
from django.db import migrations, models

TAMANHO_NOME = 150


def desduplicar_nomes(apps, schema_editor):
    """O nome passa a identificar o cupom na conta: repetidos ganham " (2)", " (3)"
    por ordem de id (o mais antigo fica com o nome), senao o indice unico nao nasce."""
    Cupom = apps.get_model("loja", "Cupom")
    usados = {}
    for _pk, conta, nome in Cupom.objects.order_by("pk").values_list("pk", "account_id", "name"):
        usados.setdefault(conta, set()).add(nome)
    vistos = {}
    for pk, conta, nome in Cupom.objects.order_by("pk").values_list("pk", "account_id", "name"):
        ja_vistos = vistos.setdefault(conta, set())
        if nome not in ja_vistos:
            ja_vistos.add(nome)
            continue
        numero = 2
        while True:
            sufixo = f" ({numero})"
            novo = nome[:TAMANHO_NOME - len(sufixo)] + sufixo
            if novo not in usados[conta]:
                break
            numero += 1
        usados[conta].add(novo)
        ja_vistos.add(novo)
        Cupom.objects.filter(pk=pk).update(name=novo)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_grupos_e_perfis_padrao'),
        ('loja', '0007_alter_historicalproduto_descricao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupom',
            name='code',
            field=models.CharField(default=apps.loja.models.cupom.gerar_codigo, editable=False, max_length=100, verbose_name='codigo'),
        ),
        migrations.AlterField(
            model_name='historicalcupom',
            name='code',
            field=models.CharField(default=apps.loja.models.cupom.gerar_codigo, editable=False, max_length=100, verbose_name='codigo'),
        ),
        migrations.RunPython(desduplicar_nomes, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='cupom',
            constraint=models.UniqueConstraint(fields=('account', 'name'), name='cupom_nome_conta_unico'),
        ),
    ]
