# Generated by Django 5.1.15 on 2026-10-01 08:01

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0009_cupom_shopify_no_vinculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='metadados',
            field=models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='metadados'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='metadados',
            field=models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='metadados'),
        ),
        migrations.AlterField(
            model_name='clienteendereco',
            name='metadados',
            field=models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='metadados'),
        ),
        migrations.AlterField(
            model_name='cupom',
            name='metadados',
            field=models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='metadados'),
        ),
        migrations.AlterField(
            model_name='entregapedido',
            name='metadados',
            field=models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='metadados'),
        ),
        migrations.AlterField(
            model_name='historicalcategoria',
            name='metadados',
            field=models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='metadados'),
        ),
        migrations.AlterField(
            model_name='historicalcliente',
            name='metadados',
            field=models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='metadados'),
        ),
        migrations.AlterField(
            model_name='historicalclienteendereco',
            name='metadados',
            field=models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='metadados'),
        ),
        migrations.AlterField(
            model_name='historicalcupom',
            name='metadados',
            field=models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='metadados'),
        ),
        migrations.AlterField(
            model_name='historicalentregapedido',
            name='metadados',
            field=models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='metadados'),
        ),
        migrations.AlterField(
            model_name='historicalitembundle',
            name='metadados',
            field=models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='metadados'),
        ),
        migrations.AlterField(
            model_name='historicalitempedido',
            name='metadados',
            field=models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='metadados'),
        ),
        migrations.AlterField(
            model_name='historicalmidiaproduto',
            name='metadados',
            field=models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='metadados'),
        ),
        migrations.AlterField(
            model_name='historicalpagamentopedido',
            name='metadados',
            field=models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='metadados'),
        ),
        migrations.AlterField(
            model_name='historicalpedido',
            name='metadados',
            field=models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='metadados'),
        ),
        migrations.AlterField(
            model_name='historicalproduto',
            name='metadados',
            field=models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='metadados'),
        ),
        migrations.AlterField(
            model_name='historicaltag',
            name='metadados',
            field=models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='metadados'),
        ),
        migrations.AlterField(
            model_name='historicaltipovariante',
            name='metadados',
            field=models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='metadados'),
        ),
        migrations.AlterField(
            model_name='historicalvalordavarianteproduto',
            name='metadados',
            field=models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='metadados'),
        ),
        migrations.AlterField(
            model_name='historicalvalorvariante',
            name='metadados',
            field=models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='metadados'),
        ),
        migrations.AlterField(
            model_name='historicalvarianteproduto',
            name='metadados',
            field=models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='metadados'),
        ),
        migrations.AlterField(
            model_name='itembundle',
            name='metadados',
            field=models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='metadados'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='metadados',
            field=models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='metadados'),
        ),
        migrations.AlterField(
            model_name='midiaproduto',
            name='metadados',
            field=models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='metadados'),
        ),
        migrations.AlterField(
            model_name='pagamentopedido',
            name='metadados',
            field=models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='metadados'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='metadados',
            field=models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='metadados'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='metadados',
            field=models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='metadados'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='metadados',
            field=models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='metadados'),
        ),
        migrations.AlterField(
            model_name='tipovariante',
            name='metadados',
            field=models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='metadados'),
        ),
        migrations.AlterField(
            model_name='valordavarianteproduto',
            name='metadados',
            field=models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='metadados'),
        ),
        migrations.AlterField(
            model_name='valorvariante',
            name='metadados',
            field=models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='metadados'),
        ),
        migrations.AlterField(
            model_name='varianteproduto',
            name='metadados',
            field=models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='metadados'),
        ),
    ]
