# Generated by Django 5.1.15 on 2026-10-03 17:19

import django.core.serializers.json
import django.db.models.deletion
import django.db.models.manager
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_uuid_unico'),
        ('loja', '0014_pedido_numero_do_hub'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='uuid')),
                ('active', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('origin', models.CharField(choices=[('starhub', 'StarHub'), ('shopify', 'Shopify'), ('woocommerce', 'WooCommerce'), ('mercado_livre', 'Mercado Livre'), ('shopee', 'Shopee'), ('amazon', 'Amazon'), ('magalu', 'Magalu'), ('api', 'API'), ('import', 'Importacao')], default='starhub', max_length=30, verbose_name='origem')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='alterado em')),
                ('metadados', models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='metadados')),
                ('nome_publico', models.CharField(max_length=80, verbose_name='nome publico')),
                ('nota', models.PositiveSmallIntegerField(verbose_name='nota')),
                ('comentario', models.TextField(max_length=1500, verbose_name='comentario')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada')], db_index=True, default='pendente', max_length=20, verbose_name='status')),
                ('motivo_rejeicao', models.CharField(blank=True, max_length=255, verbose_name='motivo da rejeicao')),
                ('moderado_em', models.DateTimeField(blank=True, null=True, verbose_name='moderado em')),
                ('compra_verificada', models.BooleanField(default=False, verbose_name='compra verificada')),
                ('publicada_em', models.DateTimeField(blank=True, null=True, verbose_name='publicada na loja em')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.account', verbose_name='conta')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avaliacoes', to='loja.cliente', verbose_name='cliente')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('moderado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='moderado por')),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='loja.pedido', verbose_name='pedido')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avaliacoes', to='loja.produto', verbose_name='produto')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='alterado por')),
            ],
            options={
                'verbose_name': 'avaliacao',
                'verbose_name_plural': 'avaliacoes',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='FotoAvaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='uuid')),
                ('active', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('origin', models.CharField(choices=[('starhub', 'StarHub'), ('shopify', 'Shopify'), ('woocommerce', 'WooCommerce'), ('mercado_livre', 'Mercado Livre'), ('shopee', 'Shopee'), ('amazon', 'Amazon'), ('magalu', 'Magalu'), ('api', 'API'), ('import', 'Importacao')], default='starhub', max_length=30, verbose_name='origem')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='alterado em')),
                ('metadados', models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='metadados')),
                ('imagem', models.FileField(upload_to='avaliacoes/%Y/%m/', verbose_name='imagem')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='ordem')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.account', verbose_name='conta')),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='loja.avaliacao', verbose_name='avaliacao')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='alterado por')),
            ],
            options={
                'verbose_name': 'foto da avaliacao',
                'verbose_name_plural': 'fotos da avaliacao',
                'ordering': ['ordem'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalAvaliacao',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='uuid')),
                ('active', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('origin', models.CharField(choices=[('starhub', 'StarHub'), ('shopify', 'Shopify'), ('woocommerce', 'WooCommerce'), ('mercado_livre', 'Mercado Livre'), ('shopee', 'Shopee'), ('amazon', 'Amazon'), ('magalu', 'Magalu'), ('api', 'API'), ('import', 'Importacao')], default='starhub', max_length=30, verbose_name='origem')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='alterado em')),
                ('metadados', models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='metadados')),
                ('nome_publico', models.CharField(max_length=80, verbose_name='nome publico')),
                ('nota', models.PositiveSmallIntegerField(verbose_name='nota')),
                ('comentario', models.TextField(max_length=1500, verbose_name='comentario')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada')], db_index=True, default='pendente', max_length=20, verbose_name='status')),
                ('motivo_rejeicao', models.CharField(blank=True, max_length=255, verbose_name='motivo da rejeicao')),
                ('moderado_em', models.DateTimeField(blank=True, null=True, verbose_name='moderado em')),
                ('compra_verificada', models.BooleanField(default=False, verbose_name='compra verificada')),
                ('publicada_em', models.DateTimeField(blank=True, null=True, verbose_name='publicada na loja em')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('account', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.account', verbose_name='conta')),
                ('cliente', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='loja.cliente', verbose_name='cliente')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('moderado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='moderado por')),
                ('pedido', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='loja.pedido', verbose_name='pedido')),
                ('produto', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='loja.produto', verbose_name='produto')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='alterado por')),
            ],
            options={
                'verbose_name': 'historical avaliacao',
                'verbose_name_plural': 'historical avaliacoes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalFotoAvaliacao',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='uuid')),
                ('active', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('origin', models.CharField(choices=[('starhub', 'StarHub'), ('shopify', 'Shopify'), ('woocommerce', 'WooCommerce'), ('mercado_livre', 'Mercado Livre'), ('shopee', 'Shopee'), ('amazon', 'Amazon'), ('magalu', 'Magalu'), ('api', 'API'), ('import', 'Importacao')], default='starhub', max_length=30, verbose_name='origem')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='alterado em')),
                ('metadados', models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='metadados')),
                ('imagem', models.TextField(max_length=100, verbose_name='imagem')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='ordem')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('account', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.account', verbose_name='conta')),
                ('avaliacao', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='loja.avaliacao', verbose_name='avaliacao')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='alterado por')),
            ],
            options={
                'verbose_name': 'historical foto da avaliacao',
                'verbose_name_plural': 'historical fotos da avaliacao',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddConstraint(
            model_name='avaliacao',
            constraint=models.UniqueConstraint(fields=('account', 'produto', 'cliente'), name='avaliacao_unica_por_cliente'),
        ),
        migrations.AddConstraint(
            model_name='avaliacao',
            constraint=models.CheckConstraint(condition=models.Q(('nota__gte', 1), ('nota__lte', 5)), name='avaliacao_nota_1_a_5'),
        ),
        migrations.AddConstraint(
            model_name='fotoavaliacao',
            constraint=models.UniqueConstraint(fields=('avaliacao', 'ordem'), name='foto_avaliacao_ordem_unica'),
        ),
    ]
