# Generated by Django 5.1.15 on 2026-10-04 11:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_uuid_unico'),
        ('loja', '0015_avaliacoes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='avaliacao',
            name='avaliacao_unica_por_cliente',
        ),
        migrations.AddConstraint(
            model_name='avaliacao',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'rejeitada'), _negated=True), fields=('account', 'produto', 'cliente'), name='avaliacao_unica_por_cliente'),
        ),
    ]
