# Generated by Django 5.1.15 on 2026-10-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0016_avaliacao_rejeitada_libera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='origin',
            field=models.CharField(choices=[('starhub', 'StarHub'), ('shopify', 'Shopify'), ('woocommerce', 'WooCommerce'), ('suri', 'Suri Shop'), ('mercado_livre', 'Mercado Livre'), ('shopee', 'Shopee'), ('amazon', 'Amazon'), ('magalu', 'Magalu'), ('api', 'API'), ('import', 'Importacao')], default='starhub', max_length=30, verbose_name='origem'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='origin',
            field=models.CharField(choices=[('starhub', 'StarHub'), ('shopify', 'Shopify'), ('woocommerce', 'WooCommerce'), ('suri', 'Suri Shop'), ('mercado_livre', 'Mercado Livre'), ('shopee', 'Shopee'), ('amazon', 'Amazon'), ('magalu', 'Magalu'), ('api', 'API'), ('import', 'Importacao')], default='starhub', max_length=30, verbose_name='origem'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='origin',
            field=models.CharField(choices=[('starhub', 'StarHub'), ('shopify', 'Shopify'), ('woocommerce', 'WooCommerce'), ('suri', 'Suri Shop'), ('mercado_livre', 'Mercado Livre'), ('shopee', 'Shopee'), ('amazon', 'Amazon'), ('magalu', 'Magalu'), ('api', 'API'), ('import', 'Importacao')], default='starhub', max_length=30, verbose_name='origem'),
        ),
        migrations.AlterField(
            model_name='clienteendereco',
            name='origin',
            field=models.CharField(choices=[('starhub', 'StarHub'), ('shopify', 'Shopify'), ('woocommerce', 'WooCommerce'), ('suri', 'Suri Shop'), ('mercado_livre', 'Mercado Livre'), ('shopee', 'Shopee'), ('amazon', 'Amazon'), ('magalu', 'Magalu'), ('api', 'API'), ('import', 'Importacao')], default='starhub', max_length=30, verbose_name='origem'),
        ),
        migrations.AlterField(
            model_name='cupom',
            name='origin',
            field=models.CharField(choices=[('starhub', 'StarHub'), ('shopify', 'Shopify'), ('woocommerce', 'WooCommerce'), ('suri', 'Suri Shop'), ('mercado_livre', 'Mercado Livre'), ('shopee', 'Shopee'), ('amazon', 'Amazon'), ('magalu', 'Magalu'), ('api', 'API'), ('import', 'Importacao')], default='starhub', max_length=30, verbose_name='origem'),
        ),
        migrations.AlterField(
            model_name='entregapedido',
            name='origin',
            field=models.CharField(choices=[('starhub', 'StarHub'), ('shopify', 'Shopify'), ('woocommerce', 'WooCommerce'), ('suri', 'Suri Shop'), ('mercado_livre', 'Mercado Livre'), ('shopee', 'Shopee'), ('amazon', 'Amazon'), ('magalu', 'Magalu'), ('api', 'API'), ('import', 'Importacao')], default='starhub', max_length=30, verbose_name='origem'),
        ),
        migrations.AlterField(
            model_name='fotoavaliacao',
            name='origin',
            field=models.CharField(choices=[('starhub', 'StarHub'), ('shopify', 'Shopify'), ('woocommerce', 'WooCommerce'), ('suri', 'Suri Shop'), ('mercado_livre', 'Mercado Livre'), ('shopee', 'Shopee'), ('amazon', 'Amazon'), ('magalu', 'Magalu'), ('api', 'API'), ('import', 'Importacao')], default='starhub', max_length=30, verbose_name='origem'),
        ),
        migrations.AlterField(
            model_name='historicalavaliacao',
            name='origin',
            field=models.CharField(choices=[('starhub', 'StarHub'), ('shopify', 'Shopify'), ('woocommerce', 'WooCommerce'), ('suri', 'Suri Shop'), ('mercado_livre', 'Mercado Livre'), ('shopee', 'Shopee'), ('amazon', 'Amazon'), ('magalu', 'Magalu'), ('api', 'API'), ('import', 'Importacao')], default='starhub', max_length=30, verbose_name='origem'),
        ),
        migrations.AlterField(
            model_name='historicalcategoria',
            name='origin',
            field=models.CharField(choices=[('starhub', 'StarHub'), ('shopify', 'Shopify'), ('woocommerce', 'WooCommerce'), ('suri', 'Suri Shop'), ('mercado_livre', 'Mercado Livre'), ('shopee', 'Shopee'), ('amazon', 'Amazon'), ('magalu', 'Magalu'), ('api', 'API'), ('import', 'Importacao')], default='starhub', max_length=30, verbose_name='origem'),
        ),
        migrations.AlterField(
            model_name='historicalcliente',
            name='origin',
            field=models.CharField(choices=[('starhub', 'StarHub'), ('shopify', 'Shopify'), ('woocommerce', 'WooCommerce'), ('suri', 'Suri Shop'), ('mercado_livre', 'Mercado Livre'), ('shopee', 'Shopee'), ('amazon', 'Amazon'), ('magalu', 'Magalu'), ('api', 'API'), ('import', 'Importacao')], default='starhub', max_length=30, verbose_name='origem'),
        ),
        migrations.AlterField(
            model_name='historicalclienteendereco',
            name='origin',
            field=models.CharField(choices=[('starhub', 'StarHub'), ('shopify', 'Shopify'), ('woocommerce', 'WooCommerce'), ('suri', 'Suri Shop'), ('mercado_livre', 'Mercado Livre'), ('shopee', 'Shopee'), ('amazon', 'Amazon'), ('magalu', 'Magalu'), ('api', 'API'), ('import', 'Importacao')], default='starhub', max_length=30, verbose_name='origem'),
        ),
        migrations.AlterField(
            model_name='historicalcupom',
            name='origin',
            field=models.CharField(choices=[('starhub', 'StarHub'), ('shopify', 'Shopify'), ('woocommerce', 'WooCommerce'), ('suri', 'Suri Shop'), ('mercado_livre', 'Mercado Livre'), ('shopee', 'Shopee'), ('amazon', 'Amazon'), ('magalu', 'Magalu'), ('api', 'API'), ('import', 'Importacao')], default='starhub', max_length=30, verbose_name='origem'),
        ),
        migrations.AlterField(
            model_name='historicalentregapedido',
            name='origin',
            field=models.CharField(choices=[('starhub', 'StarHub'), ('shopify', 'Shopify'), ('woocommerce', 'WooCommerce'), ('suri', 'Suri Shop'), ('mercado_livre', 'Mercado Livre'), ('shopee', 'Shopee'), ('amazon', 'Amazon'), ('magalu', 'Magalu'), ('api', 'API'), ('import', 'Importacao')], default='starhub', max_length=30, verbose_name='origem'),
        ),
        migrations.AlterField(
            model_name='historicalfotoavaliacao',
            name='origin',
            field=models.CharField(choices=[('starhub', 'StarHub'), ('shopify', 'Shopify'), ('woocommerce', 'WooCommerce'), ('suri', 'Suri Shop'), ('mercado_livre', 'Mercado Livre'), ('shopee', 'Shopee'), ('amazon', 'Amazon'), ('magalu', 'Magalu'), ('api', 'API'), ('import', 'Importacao')], default='starhub', max_length=30, verbose_name='origem'),
        ),
        migrations.AlterField(
            model_name='historicalitembundle',
            name='origin',
            field=models.CharField(choices=[('starhub', 'StarHub'), ('shopify', 'Shopify'), ('woocommerce', 'WooCommerce'), ('suri', 'Suri Shop'), ('mercado_livre', 'Mercado Livre'), ('shopee', 'Shopee'), ('amazon', 'Amazon'), ('magalu', 'Magalu'), ('api', 'API'), ('import', 'Importacao')], default='starhub', max_length=30, verbose_name='origem'),
        ),
        migrations.AlterField(
            model_name='historicalitempedido',
            name='origin',
            field=models.CharField(choices=[('starhub', 'StarHub'), ('shopify', 'Shopify'), ('woocommerce', 'WooCommerce'), ('suri', 'Suri Shop'), ('mercado_livre', 'Mercado Livre'), ('shopee', 'Shopee'), ('amazon', 'Amazon'), ('magalu', 'Magalu'), ('api', 'API'), ('import', 'Importacao')], default='starhub', max_length=30, verbose_name='origem'),
        ),
        migrations.AlterField(
            model_name='historicalmidiaproduto',
            name='origin',
            field=models.CharField(choices=[('starhub', 'StarHub'), ('shopify', 'Shopify'), ('woocommerce', 'WooCommerce'), ('suri', 'Suri Shop'), ('mercado_livre', 'Mercado Livre'), ('shopee', 'Shopee'), ('amazon', 'Amazon'), ('magalu', 'Magalu'), ('api', 'API'), ('import', 'Importacao')], default='starhub', max_length=30, verbose_name='origem'),
        ),
        migrations.AlterField(
            model_name='historicalpagamentopedido',
            name='origin',
            field=models.CharField(choices=[('starhub', 'StarHub'), ('shopify', 'Shopify'), ('woocommerce', 'WooCommerce'), ('suri', 'Suri Shop'), ('mercado_livre', 'Mercado Livre'), ('shopee', 'Shopee'), ('amazon', 'Amazon'), ('magalu', 'Magalu'), ('api', 'API'), ('import', 'Importacao')], default='starhub', max_length=30, verbose_name='origem'),
        ),
        migrations.AlterField(
            model_name='historicalpedido',
            name='origin',
            field=models.CharField(choices=[('starhub', 'StarHub'), ('shopify', 'Shopify'), ('woocommerce', 'WooCommerce'), ('suri', 'Suri Shop'), ('mercado_livre', 'Mercado Livre'), ('shopee', 'Shopee'), ('amazon', 'Amazon'), ('magalu', 'Magalu'), ('api', 'API'), ('import', 'Importacao')], default='starhub', max_length=30, verbose_name='origem'),
        ),
        migrations.AlterField(
            model_name='historicalproduto',
            name='origin',
            field=models.CharField(choices=[('starhub', 'StarHub'), ('shopify', 'Shopify'), ('woocommerce', 'WooCommerce'), ('suri', 'Suri Shop'), ('mercado_livre', 'Mercado Livre'), ('shopee', 'Shopee'), ('amazon', 'Amazon'), ('magalu', 'Magalu'), ('api', 'API'), ('import', 'Importacao')], default='starhub', max_length=30, verbose_name='origem'),
        ),
        migrations.AlterField(
            model_name='historicaltag',
            name='origin',
            field=models.CharField(choices=[('starhub', 'StarHub'), ('shopify', 'Shopify'), ('woocommerce', 'WooCommerce'), ('suri', 'Suri Shop'), ('mercado_livre', 'Mercado Livre'), ('shopee', 'Shopee'), ('amazon', 'Amazon'), ('magalu', 'Magalu'), ('api', 'API'), ('import', 'Importacao')], default='starhub', max_length=30, verbose_name='origem'),
        ),
        migrations.AlterField(
            model_name='historicaltipovariante',
            name='origin',
            field=models.CharField(choices=[('starhub', 'StarHub'), ('shopify', 'Shopify'), ('woocommerce', 'WooCommerce'), ('suri', 'Suri Shop'), ('mercado_livre', 'Mercado Livre'), ('shopee', 'Shopee'), ('amazon', 'Amazon'), ('magalu', 'Magalu'), ('api', 'API'), ('import', 'Importacao')], default='starhub', max_length=30, verbose_name='origem'),
        ),
        migrations.AlterField(
            model_name='historicalvalordavarianteproduto',
            name='origin',
            field=models.CharField(choices=[('starhub', 'StarHub'), ('shopify', 'Shopify'), ('woocommerce', 'WooCommerce'), ('suri', 'Suri Shop'), ('mercado_livre', 'Mercado Livre'), ('shopee', 'Shopee'), ('amazon', 'Amazon'), ('magalu', 'Magalu'), ('api', 'API'), ('import', 'Importacao')], default='starhub', max_length=30, verbose_name='origem'),
        ),
        migrations.AlterField(
            model_name='historicalvalorvariante',
            name='origin',
            field=models.CharField(choices=[('starhub', 'StarHub'), ('shopify', 'Shopify'), ('woocommerce', 'WooCommerce'), ('suri', 'Suri Shop'), ('mercado_livre', 'Mercado Livre'), ('shopee', 'Shopee'), ('amazon', 'Amazon'), ('magalu', 'Magalu'), ('api', 'API'), ('import', 'Importacao')], default='starhub', max_length=30, verbose_name='origem'),
        ),
        migrations.AlterField(
            model_name='historicalvarianteproduto',
            name='origin',
            field=models.CharField(choices=[('starhub', 'StarHub'), ('shopify', 'Shopify'), ('woocommerce', 'WooCommerce'), ('suri', 'Suri Shop'), ('mercado_livre', 'Mercado Livre'), ('shopee', 'Shopee'), ('amazon', 'Amazon'), ('magalu', 'Magalu'), ('api', 'API'), ('import', 'Importacao')], default='starhub', max_length=30, verbose_name='origem'),
        ),
        migrations.AlterField(
            model_name='itembundle',
            name='origin',
            field=models.CharField(choices=[('starhub', 'StarHub'), ('shopify', 'Shopify'), ('woocommerce', 'WooCommerce'), ('suri', 'Suri Shop'), ('mercado_livre', 'Mercado Livre'), ('shopee', 'Shopee'), ('amazon', 'Amazon'), ('magalu', 'Magalu'), ('api', 'API'), ('import', 'Importacao')], default='starhub', max_length=30, verbose_name='origem'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='origin',
            field=models.CharField(choices=[('starhub', 'StarHub'), ('shopify', 'Shopify'), ('woocommerce', 'WooCommerce'), ('suri', 'Suri Shop'), ('mercado_livre', 'Mercado Livre'), ('shopee', 'Shopee'), ('amazon', 'Amazon'), ('magalu', 'Magalu'), ('api', 'API'), ('import', 'Importacao')], default='starhub', max_length=30, verbose_name='origem'),
        ),
        migrations.AlterField(
            model_name='midiaproduto',
            name='origin',
            field=models.CharField(choices=[('starhub', 'StarHub'), ('shopify', 'Shopify'), ('woocommerce', 'WooCommerce'), ('suri', 'Suri Shop'), ('mercado_livre', 'Mercado Livre'), ('shopee', 'Shopee'), ('amazon', 'Amazon'), ('magalu', 'Magalu'), ('api', 'API'), ('import', 'Importacao')], default='starhub', max_length=30, verbose_name='origem'),
        ),
        migrations.AlterField(
            model_name='pagamentopedido',
            name='origin',
            field=models.CharField(choices=[('starhub', 'StarHub'), ('shopify', 'Shopify'), ('woocommerce', 'WooCommerce'), ('suri', 'Suri Shop'), ('mercado_livre', 'Mercado Livre'), ('shopee', 'Shopee'), ('amazon', 'Amazon'), ('magalu', 'Magalu'), ('api', 'API'), ('import', 'Importacao')], default='starhub', max_length=30, verbose_name='origem'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='origin',
            field=models.CharField(choices=[('starhub', 'StarHub'), ('shopify', 'Shopify'), ('woocommerce', 'WooCommerce'), ('suri', 'Suri Shop'), ('mercado_livre', 'Mercado Livre'), ('shopee', 'Shopee'), ('amazon', 'Amazon'), ('magalu', 'Magalu'), ('api', 'API'), ('import', 'Importacao')], default='starhub', max_length=30, verbose_name='origem'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='origin',
            field=models.CharField(choices=[('starhub', 'StarHub'), ('shopify', 'Shopify'), ('woocommerce', 'WooCommerce'), ('suri', 'Suri Shop'), ('mercado_livre', 'Mercado Livre'), ('shopee', 'Shopee'), ('amazon', 'Amazon'), ('magalu', 'Magalu'), ('api', 'API'), ('import', 'Importacao')], default='starhub', max_length=30, verbose_name='origem'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='origin',
            field=models.CharField(choices=[('starhub', 'StarHub'), ('shopify', 'Shopify'), ('woocommerce', 'WooCommerce'), ('suri', 'Suri Shop'), ('mercado_livre', 'Mercado Livre'), ('shopee', 'Shopee'), ('amazon', 'Amazon'), ('magalu', 'Magalu'), ('api', 'API'), ('import', 'Importacao')], default='starhub', max_length=30, verbose_name='origem'),
        ),
        migrations.AlterField(
            model_name='tipovariante',
            name='origin',
            field=models.CharField(choices=[('starhub', 'StarHub'), ('shopify', 'Shopify'), ('woocommerce', 'WooCommerce'), ('suri', 'Suri Shop'), ('mercado_livre', 'Mercado Livre'), ('shopee', 'Shopee'), ('amazon', 'Amazon'), ('magalu', 'Magalu'), ('api', 'API'), ('import', 'Importacao')], default='starhub', max_length=30, verbose_name='origem'),
        ),
        migrations.AlterField(
            model_name='valordavarianteproduto',
            name='origin',
            field=models.CharField(choices=[('starhub', 'StarHub'), ('shopify', 'Shopify'), ('woocommerce', 'WooCommerce'), ('suri', 'Suri Shop'), ('mercado_livre', 'Mercado Livre'), ('shopee', 'Shopee'), ('amazon', 'Amazon'), ('magalu', 'Magalu'), ('api', 'API'), ('import', 'Importacao')], default='starhub', max_length=30, verbose_name='origem'),
        ),
        migrations.AlterField(
            model_name='valorvariante',
            name='origin',
            field=models.CharField(choices=[('starhub', 'StarHub'), ('shopify', 'Shopify'), ('woocommerce', 'WooCommerce'), ('suri', 'Suri Shop'), ('mercado_livre', 'Mercado Livre'), ('shopee', 'Shopee'), ('amazon', 'Amazon'), ('magalu', 'Magalu'), ('api', 'API'), ('import', 'Importacao')], default='starhub', max_length=30, verbose_name='origem'),
        ),
        migrations.AlterField(
            model_name='varianteproduto',
            name='origin',
            field=models.CharField(choices=[('starhub', 'StarHub'), ('shopify', 'Shopify'), ('woocommerce', 'WooCommerce'), ('suri', 'Suri Shop'), ('mercado_livre', 'Mercado Livre'), ('shopee', 'Shopee'), ('amazon', 'Amazon'), ('magalu', 'Magalu'), ('api', 'API'), ('import', 'Importacao')], default='starhub', max_length=30, verbose_name='origem'),
        ),
    ]
