# Generated by Django 5.1.15 on 2026-10-07 12:28

import django.core.serializers.json
import django.db.models.deletion
import django.db.models.manager
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_dominios_avaliacoes_lista'),
        ('loja', '0017_plataformas_woocommerce_suri'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalServico',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='uuid')),
                ('active', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('origin', models.CharField(choices=[('starhub', 'StarHub'), ('shopify', 'Shopify'), ('woocommerce', 'WooCommerce'), ('suri', 'Suri Shop'), ('mercado_livre', 'Mercado Livre'), ('shopee', 'Shopee'), ('amazon', 'Amazon'), ('magalu', 'Magalu'), ('api', 'API'), ('import', 'Importacao')], default='starhub', max_length=30, verbose_name='origem')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='alterado em')),
                ('metadados', models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='metadados')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('nome_normalizado', models.CharField(editable=False, max_length=150)),
                ('sku', models.CharField(help_text='Codigo do servico no ERP. Nasce como SERV-<NOME> quando o servico chega num pedido sem cadastro; troque pelo codigo do ERP.', max_length=100, verbose_name='SKU')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('account', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.account', verbose_name='conta')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='alterado por')),
            ],
            options={
                'verbose_name': 'historical servico',
                'verbose_name_plural': 'historical servicos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='uuid')),
                ('active', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('origin', models.CharField(choices=[('starhub', 'StarHub'), ('shopify', 'Shopify'), ('woocommerce', 'WooCommerce'), ('suri', 'Suri Shop'), ('mercado_livre', 'Mercado Livre'), ('shopee', 'Shopee'), ('amazon', 'Amazon'), ('magalu', 'Magalu'), ('api', 'API'), ('import', 'Importacao')], default='starhub', max_length=30, verbose_name='origem')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='alterado em')),
                ('metadados', models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='metadados')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('nome_normalizado', models.CharField(editable=False, max_length=150)),
                ('sku', models.CharField(help_text='Codigo do servico no ERP. Nasce como SERV-<NOME> quando o servico chega num pedido sem cadastro; troque pelo codigo do ERP.', max_length=100, verbose_name='SKU')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.account', verbose_name='conta')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='alterado por')),
            ],
            options={
                'verbose_name': 'servico',
                'verbose_name_plural': 'servicos',
                'ordering': ['nome'],
                'constraints': [models.UniqueConstraint(fields=('account', 'nome_normalizado'), name='servico_nome_conta_unico'), models.UniqueConstraint(fields=('account', 'sku'), name='servico_sku_conta_unico')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
