# Generated by Django 5.1.15 on 2026-10-07 17:40

import django.core.serializers.json
import django.core.validators
import django.db.models.deletion
import django.db.models.manager
import simple_history.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_dominios_avaliacoes_lista'),
        ('loja', '0019_servicos_dos_pedidos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalservico',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Vale para os produtos das regras que nao tem preco proprio.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='preco padrao'),
        ),
        migrations.AddField(
            model_name='servico',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Vale para os produtos das regras que nao tem preco proprio.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='preco padrao'),
        ),
        migrations.CreateModel(
            name='HistoricalRegraServico',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='uuid')),
                ('active', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('origin', models.CharField(choices=[('starhub', 'StarHub'), ('shopify', 'Shopify'), ('woocommerce', 'WooCommerce'), ('suri', 'Suri Shop'), ('mercado_livre', 'Mercado Livre'), ('shopee', 'Shopee'), ('amazon', 'Amazon'), ('magalu', 'Magalu'), ('api', 'API'), ('import', 'Importacao')], default='starhub', max_length=30, verbose_name='origem')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='alterado em')),
                ('metadados', models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='metadados')),
                ('ordem', models.PositiveIntegerField(default=10, help_text='Menor primeiro. O produto que cai em duas regras fica com a de menor ordem.', verbose_name='ordem')),
                ('preco_de', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='preco do produto a partir de')),
                ('preco_ate', models.DecimalField(blank=True, decimal_places=2, help_text='Faixa pelo preco da variante padrao do produto.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='preco do produto ate')),
                ('preco', models.DecimalField(blank=True, decimal_places=2, help_text='Vazio: vale o preco padrao do servico.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='preco do servico')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('account', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.account', verbose_name='conta')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('servico', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='loja.servico', verbose_name='servico')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='alterado por')),
            ],
            options={
                'verbose_name': 'historical regra do servico',
                'verbose_name_plural': 'historical regras do servico',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='RegraServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='uuid')),
                ('active', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('origin', models.CharField(choices=[('starhub', 'StarHub'), ('shopify', 'Shopify'), ('woocommerce', 'WooCommerce'), ('suri', 'Suri Shop'), ('mercado_livre', 'Mercado Livre'), ('shopee', 'Shopee'), ('amazon', 'Amazon'), ('magalu', 'Magalu'), ('api', 'API'), ('import', 'Importacao')], default='starhub', max_length=30, verbose_name='origem')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='alterado em')),
                ('metadados', models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='metadados')),
                ('ordem', models.PositiveIntegerField(default=10, help_text='Menor primeiro. O produto que cai em duas regras fica com a de menor ordem.', verbose_name='ordem')),
                ('preco_de', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='preco do produto a partir de')),
                ('preco_ate', models.DecimalField(blank=True, decimal_places=2, help_text='Faixa pelo preco da variante padrao do produto.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='preco do produto ate')),
                ('preco', models.DecimalField(blank=True, decimal_places=2, help_text='Vazio: vale o preco padrao do servico.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='preco do servico')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.account', verbose_name='conta')),
                ('categorias', models.ManyToManyField(blank=True, related_name='regras_servico', to='loja.categoria', verbose_name='categorias')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('produtos', models.ManyToManyField(blank=True, related_name='regras_servico', to='loja.produto', verbose_name='produtos')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regras', to='loja.servico', verbose_name='servico')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='alterado por')),
            ],
            options={
                'verbose_name': 'regra do servico',
                'verbose_name_plural': 'regras do servico',
                'ordering': ['servico', 'ordem', 'pk'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
