# Generated by Django 5.1.15 on 2026-10-04 15:03

import django.core.serializers.json
import django.core.validators
import django.db.models.deletion
import django.db.models.manager
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0007_uuid_unico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoordenadaCep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=8, unique=True, verbose_name='CEP')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('fonte', models.CharField(max_length=30, verbose_name='fonte')),
                ('consultado_em', models.DateTimeField(auto_now=True, verbose_name='consultado em')),
            ],
            options={
                'verbose_name': 'coordenada de CEP',
                'verbose_name_plural': 'coordenadas de CEP',
            },
        ),
        migrations.CreateModel(
            name='HistoricalTabelaFrete',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='uuid')),
                ('active', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('origin', models.CharField(choices=[('starhub', 'StarHub'), ('shopify', 'Shopify'), ('woocommerce', 'WooCommerce'), ('mercado_livre', 'Mercado Livre'), ('shopee', 'Shopee'), ('amazon', 'Amazon'), ('magalu', 'Magalu'), ('api', 'API'), ('import', 'Importacao')], default='starhub', max_length=30, verbose_name='origem')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='alterado em')),
                ('metadados', models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='metadados')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('tipo', models.CharField(choices=[('distancia', 'Por distancia (km)'), ('faixa_cep', 'Por faixa de CEP')], default='distancia', max_length=20, verbose_name='forma de cobranca')),
                ('prazo_dias', models.PositiveSmallIntegerField(default=0, help_text='Por distancia: prazo de toda entrega. Por faixa: vale para a faixa sem prazo.', verbose_name='prazo (dias uteis)')),
                ('cep_origem', models.CharField(blank=True, help_text='De onde a entrega sai (deposito ou loja).', max_length=8, validators=[django.core.validators.RegexValidator('^\\d{8}$', 'Informe o CEP com 8 digitos, por exemplo 01001-000.')], verbose_name='CEP de origem')),
                ('preco_por_km', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='preco por km')),
                ('taxa_fixa', models.DecimalField(decimal_places=2, default=0, help_text='Somada a toda entrega, alem do valor por km.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='taxa fixa')),
                ('valor_minimo', models.DecimalField(decimal_places=2, default=0, help_text='Entrega perto nunca sai por menos que isto.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='valor minimo')),
                ('distancia_maxima_km', models.DecimalField(blank=True, decimal_places=1, help_text='Acima disto nao entrega. Vazio = sem limite.', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='distancia maxima (km)')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('account', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.account', verbose_name='conta')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='alterado por')),
            ],
            options={
                'verbose_name': 'historical tabela de frete',
                'verbose_name_plural': 'historical tabelas de frete',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='TabelaFrete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='uuid')),
                ('active', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('origin', models.CharField(choices=[('starhub', 'StarHub'), ('shopify', 'Shopify'), ('woocommerce', 'WooCommerce'), ('mercado_livre', 'Mercado Livre'), ('shopee', 'Shopee'), ('amazon', 'Amazon'), ('magalu', 'Magalu'), ('api', 'API'), ('import', 'Importacao')], default='starhub', max_length=30, verbose_name='origem')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='alterado em')),
                ('metadados', models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='metadados')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('tipo', models.CharField(choices=[('distancia', 'Por distancia (km)'), ('faixa_cep', 'Por faixa de CEP')], default='distancia', max_length=20, verbose_name='forma de cobranca')),
                ('prazo_dias', models.PositiveSmallIntegerField(default=0, help_text='Por distancia: prazo de toda entrega. Por faixa: vale para a faixa sem prazo.', verbose_name='prazo (dias uteis)')),
                ('cep_origem', models.CharField(blank=True, help_text='De onde a entrega sai (deposito ou loja).', max_length=8, validators=[django.core.validators.RegexValidator('^\\d{8}$', 'Informe o CEP com 8 digitos, por exemplo 01001-000.')], verbose_name='CEP de origem')),
                ('preco_por_km', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='preco por km')),
                ('taxa_fixa', models.DecimalField(decimal_places=2, default=0, help_text='Somada a toda entrega, alem do valor por km.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='taxa fixa')),
                ('valor_minimo', models.DecimalField(decimal_places=2, default=0, help_text='Entrega perto nunca sai por menos que isto.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='valor minimo')),
                ('distancia_maxima_km', models.DecimalField(blank=True, decimal_places=1, help_text='Acima disto nao entrega. Vazio = sem limite.', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='distancia maxima (km)')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.account', verbose_name='conta')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='alterado por')),
            ],
            options={
                'verbose_name': 'tabela de frete',
                'verbose_name_plural': 'tabelas de frete',
                'ordering': ['nome'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalFaixaCep',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='uuid')),
                ('active', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('origin', models.CharField(choices=[('starhub', 'StarHub'), ('shopify', 'Shopify'), ('woocommerce', 'WooCommerce'), ('mercado_livre', 'Mercado Livre'), ('shopee', 'Shopee'), ('amazon', 'Amazon'), ('magalu', 'Magalu'), ('api', 'API'), ('import', 'Importacao')], default='starhub', max_length=30, verbose_name='origem')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='alterado em')),
                ('metadados', models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='metadados')),
                ('cep_inicial', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^\\d{8}$', 'Informe o CEP com 8 digitos, por exemplo 01001-000.')], verbose_name='CEP inicial')),
                ('cep_final', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^\\d{8}$', 'Informe o CEP com 8 digitos, por exemplo 01001-000.')], verbose_name='CEP final')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='valor')),
                ('prazo_dias', models.PositiveSmallIntegerField(blank=True, help_text='Vazio = prazo da tabela.', null=True, verbose_name='prazo (dias uteis)')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('account', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.account', verbose_name='conta')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='alterado por')),
                ('tabela', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='logistica.tabelafrete', verbose_name='tabela')),
            ],
            options={
                'verbose_name': 'historical faixa de CEP',
                'verbose_name_plural': 'historical faixas de CEP',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='FaixaCep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='uuid')),
                ('active', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('origin', models.CharField(choices=[('starhub', 'StarHub'), ('shopify', 'Shopify'), ('woocommerce', 'WooCommerce'), ('mercado_livre', 'Mercado Livre'), ('shopee', 'Shopee'), ('amazon', 'Amazon'), ('magalu', 'Magalu'), ('api', 'API'), ('import', 'Importacao')], default='starhub', max_length=30, verbose_name='origem')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='alterado em')),
                ('metadados', models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='metadados')),
                ('cep_inicial', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^\\d{8}$', 'Informe o CEP com 8 digitos, por exemplo 01001-000.')], verbose_name='CEP inicial')),
                ('cep_final', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^\\d{8}$', 'Informe o CEP com 8 digitos, por exemplo 01001-000.')], verbose_name='CEP final')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='valor')),
                ('prazo_dias', models.PositiveSmallIntegerField(blank=True, help_text='Vazio = prazo da tabela.', null=True, verbose_name='prazo (dias uteis)')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.account', verbose_name='conta')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='alterado por')),
                ('tabela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faixas', to='logistica.tabelafrete', verbose_name='tabela')),
            ],
            options={
                'verbose_name': 'faixa de CEP',
                'verbose_name_plural': 'faixas de CEP',
                'ordering': ['cep_inicial'],
                'constraints': [models.CheckConstraint(condition=models.Q(('cep_inicial__lte', models.F('cep_final'))), name='faixa_cep_inicial_ate_final')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
