# Generated by Django 5.1.15 on 2026-10-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltabelafrete',
            name='no_checkout',
            field=models.BooleanField(default=False, help_text='Aparece como opcao de frete na loja, com o nome desta tabela.', verbose_name='oferecer no checkout da Shopify'),
        ),
        migrations.AddField(
            model_name='tabelafrete',
            name='no_checkout',
            field=models.BooleanField(default=False, help_text='Aparece como opcao de frete na loja, com o nome desta tabela.', verbose_name='oferecer no checkout da Shopify'),
        ),
        migrations.CreateModel(
            name='DistanciaCep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(max_length=8, verbose_name='CEP de origem')),
                ('destino', models.CharField(max_length=8, verbose_name='CEP de destino')),
                ('km', models.DecimalField(decimal_places=1, max_digits=8)),
                ('consultado_em', models.DateTimeField(auto_now=True, verbose_name='consultado em')),
            ],
            options={
                'verbose_name': 'distancia entre CEPs',
                'verbose_name_plural': 'distancias entre CEPs',
                'constraints': [models.UniqueConstraint(fields=('origem', 'destino'), name='distancia_cep_unica')],
            },
        ),
    ]
