# Generated by Django 5.1.15 on 2026-10-05 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0003_plataformas_woocommerce_suri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltabelafrete',
            name='no_checkout',
            field=models.BooleanField(default=False, help_text='Vira opcao de frete com o nome desta tabela: Shopify (cotacao na hora), WooCommerce (zonas de entrega, so faixa de CEP) e Suri (orcamento), nas lojas com o frete ligado.', verbose_name='oferecer no checkout das lojas'),
        ),
        migrations.AlterField(
            model_name='tabelafrete',
            name='no_checkout',
            field=models.BooleanField(default=False, help_text='Vira opcao de frete com o nome desta tabela: Shopify (cotacao na hora), WooCommerce (zonas de entrega, so faixa de CEP) e Suri (orcamento), nas lojas com o frete ligado.', verbose_name='oferecer no checkout das lojas'),
        ),
    ]
