# Generated by Django 5.1.15 on 2026-09-28 11:42

import apps.core.services.rules
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'endereco', 'verbose_name_plural': 'enderecos'},
        ),
        migrations.AlterModelOptions(
            name='externalreference',
            options={'verbose_name': 'referencia externa', 'verbose_name_plural': 'referencias externas'},
        ),
        migrations.AlterModelOptions(
            name='historicaladdress',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical endereco', 'verbose_name_plural': 'historical enderecos'},
        ),
        migrations.AlterModelOptions(
            name='historicalexternalreference',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical referencia externa', 'verbose_name_plural': 'historical referencias externas'},
        ),
        migrations.AlterModelOptions(
            name='historicalpublicationpolicy',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical politica de publicacao', 'verbose_name_plural': 'historical politicas de publicacao'},
        ),
        migrations.AlterModelOptions(
            name='historicalpublicationstate',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical estado de publicacao', 'verbose_name_plural': 'historical estados de publicacao'},
        ),
        migrations.AlterModelOptions(
            name='historicalsaleschannel',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical canal de venda', 'verbose_name_plural': 'historical canais de venda'},
        ),
        migrations.AlterModelOptions(
            name='publicationpolicy',
            options={'verbose_name': 'politica de publicacao', 'verbose_name_plural': 'politicas de publicacao'},
        ),
        migrations.AlterModelOptions(
            name='publicationstate',
            options={'verbose_name': 'estado de publicacao', 'verbose_name_plural': 'estados de publicacao'},
        ),
        migrations.AlterModelOptions(
            name='saleschannel',
            options={'verbose_name': 'canal de venda', 'verbose_name_plural': 'canais de venda'},
        ),
        migrations.AlterField(
            model_name='accessprofile',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='criado por'),
        ),
        migrations.AlterField(
            model_name='accessprofile',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='alterado por'),
        ),
        migrations.AlterField(
            model_name='address',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='criado por'),
        ),
        migrations.AlterField(
            model_name='address',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='alterado por'),
        ),
        migrations.AlterField(
            model_name='externalreference',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='criado por'),
        ),
        migrations.AlterField(
            model_name='externalreference',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='alterado por'),
        ),
        migrations.AlterField(
            model_name='historicalaccessprofile',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por'),
        ),
        migrations.AlterField(
            model_name='historicalaccessprofile',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='alterado por'),
        ),
        migrations.AlterField(
            model_name='historicaladdress',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por'),
        ),
        migrations.AlterField(
            model_name='historicaladdress',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='alterado por'),
        ),
        migrations.AlterField(
            model_name='historicalexternalreference',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por'),
        ),
        migrations.AlterField(
            model_name='historicalexternalreference',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='alterado por'),
        ),
        migrations.AlterField(
            model_name='historicalpublicationpolicy',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por'),
        ),
        migrations.AlterField(
            model_name='historicalpublicationpolicy',
            name='default_action',
            field=models.CharField(choices=[('allow', 'Permitir'), ('deny', 'Negar')], max_length=10, verbose_name='acao padrao'),
        ),
        migrations.AlterField(
            model_name='historicalpublicationpolicy',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='habilitada'),
        ),
        migrations.AlterField(
            model_name='historicalpublicationpolicy',
            name='entity_type',
            field=models.CharField(choices=[('product', 'Produto'), ('order', 'Pedido'), ('coupon', 'Cupom'), ('customer', 'Cliente')], max_length=20, verbose_name='tipo de entidade'),
        ),
        migrations.AlterField(
            model_name='historicalpublicationpolicy',
            name='priority',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='prioridade'),
        ),
        migrations.AlterField(
            model_name='historicalpublicationpolicy',
            name='rules',
            field=models.JSONField(blank=True, default=dict, validators=[apps.core.services.rules.validate_rules], verbose_name='regras'),
        ),
        migrations.AlterField(
            model_name='historicalpublicationpolicy',
            name='target_channel',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.saleschannel', verbose_name='canal de destino'),
        ),
        migrations.AlterField(
            model_name='historicalpublicationpolicy',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='alterado por'),
        ),
        migrations.AlterField(
            model_name='historicalpublicationstate',
            name='channel',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.saleschannel', verbose_name='canal'),
        ),
        migrations.AlterField(
            model_name='historicalpublicationstate',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por'),
        ),
        migrations.AlterField(
            model_name='historicalpublicationstate',
            name='desired_state',
            field=models.CharField(choices=[('published', 'Publicado'), ('unpublished', 'Nao publicado')], max_length=20, verbose_name='estado desejado'),
        ),
        migrations.AlterField(
            model_name='historicalpublicationstate',
            name='entity_type',
            field=models.CharField(choices=[('product', 'Produto'), ('order', 'Pedido'), ('coupon', 'Cupom'), ('customer', 'Cliente')], max_length=20, verbose_name='tipo de entidade'),
        ),
        migrations.AlterField(
            model_name='historicalpublicationstate',
            name='external_reference',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.externalreference', verbose_name='referencia externa'),
        ),
        migrations.AlterField(
            model_name='historicalpublicationstate',
            name='last_error',
            field=models.TextField(blank=True, verbose_name='ultimo erro'),
        ),
        migrations.AlterField(
            model_name='historicalpublicationstate',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ultima sincronizacao'),
        ),
        migrations.AlterField(
            model_name='historicalpublicationstate',
            name='object_id',
            field=models.CharField(max_length=64, verbose_name='id interno'),
        ),
        migrations.AlterField(
            model_name='historicalpublicationstate',
            name='payload_hash',
            field=models.CharField(blank=True, max_length=64, verbose_name='hash do conteudo'),
        ),
        migrations.AlterField(
            model_name='historicalpublicationstate',
            name='sync_status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('syncing', 'Sincronizando'), ('synced', 'Sincronizado'), ('failed', 'Falhou'), ('skipped', 'Ignorado'), ('unsupported', 'Nao suportado')], default='pending', max_length=20, verbose_name='status da sincronizacao'),
        ),
        migrations.AlterField(
            model_name='historicalpublicationstate',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='alterado por'),
        ),
        migrations.AlterField(
            model_name='historicalsaleschannel',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por'),
        ),
        migrations.AlterField(
            model_name='historicalsaleschannel',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='alterado por'),
        ),
        migrations.AlterField(
            model_name='publicationpolicy',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='criado por'),
        ),
        migrations.AlterField(
            model_name='publicationpolicy',
            name='default_action',
            field=models.CharField(choices=[('allow', 'Permitir'), ('deny', 'Negar')], max_length=10, verbose_name='acao padrao'),
        ),
        migrations.AlterField(
            model_name='publicationpolicy',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='habilitada'),
        ),
        migrations.AlterField(
            model_name='publicationpolicy',
            name='entity_type',
            field=models.CharField(choices=[('product', 'Produto'), ('order', 'Pedido'), ('coupon', 'Cupom'), ('customer', 'Cliente')], max_length=20, verbose_name='tipo de entidade'),
        ),
        migrations.AlterField(
            model_name='publicationpolicy',
            name='priority',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='prioridade'),
        ),
        migrations.AlterField(
            model_name='publicationpolicy',
            name='rules',
            field=models.JSONField(blank=True, default=dict, validators=[apps.core.services.rules.validate_rules], verbose_name='regras'),
        ),
        migrations.AlterField(
            model_name='publicationpolicy',
            name='target_channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.saleschannel', verbose_name='canal de destino'),
        ),
        migrations.AlterField(
            model_name='publicationpolicy',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='alterado por'),
        ),
        migrations.AlterField(
            model_name='publicationstate',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.saleschannel', verbose_name='canal'),
        ),
        migrations.AlterField(
            model_name='publicationstate',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='criado por'),
        ),
        migrations.AlterField(
            model_name='publicationstate',
            name='desired_state',
            field=models.CharField(choices=[('published', 'Publicado'), ('unpublished', 'Nao publicado')], max_length=20, verbose_name='estado desejado'),
        ),
        migrations.AlterField(
            model_name='publicationstate',
            name='entity_type',
            field=models.CharField(choices=[('product', 'Produto'), ('order', 'Pedido'), ('coupon', 'Cupom'), ('customer', 'Cliente')], max_length=20, verbose_name='tipo de entidade'),
        ),
        migrations.AlterField(
            model_name='publicationstate',
            name='external_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.externalreference', verbose_name='referencia externa'),
        ),
        migrations.AlterField(
            model_name='publicationstate',
            name='last_error',
            field=models.TextField(blank=True, verbose_name='ultimo erro'),
        ),
        migrations.AlterField(
            model_name='publicationstate',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ultima sincronizacao'),
        ),
        migrations.AlterField(
            model_name='publicationstate',
            name='object_id',
            field=models.CharField(max_length=64, verbose_name='id interno'),
        ),
        migrations.AlterField(
            model_name='publicationstate',
            name='payload_hash',
            field=models.CharField(blank=True, max_length=64, verbose_name='hash do conteudo'),
        ),
        migrations.AlterField(
            model_name='publicationstate',
            name='sync_status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('syncing', 'Sincronizando'), ('synced', 'Sincronizado'), ('failed', 'Falhou'), ('skipped', 'Ignorado'), ('unsupported', 'Nao suportado')], default='pending', max_length=20, verbose_name='status da sincronizacao'),
        ),
        migrations.AlterField(
            model_name='publicationstate',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='alterado por'),
        ),
        migrations.AlterField(
            model_name='saleschannel',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='criado por'),
        ),
        migrations.AlterField(
            model_name='saleschannel',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='alterado por'),
        ),
    ]
