# Generated by Django 5.1.15 on 2026-10-01 08:01

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_grupos_e_perfis_padrao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessprofile',
            name='metadados',
            field=models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='metadados'),
        ),
        migrations.AlterField(
            model_name='address',
            name='metadados',
            field=models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='metadados'),
        ),
        migrations.AlterField(
            model_name='externalreference',
            name='metadados',
            field=models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='metadados'),
        ),
        migrations.AlterField(
            model_name='historicalaccessprofile',
            name='metadados',
            field=models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='metadados'),
        ),
        migrations.AlterField(
            model_name='historicaladdress',
            name='metadados',
            field=models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='metadados'),
        ),
        migrations.AlterField(
            model_name='historicalexternalreference',
            name='metadados',
            field=models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='metadados'),
        ),
        migrations.AlterField(
            model_name='historicalpublicationpolicy',
            name='metadados',
            field=models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='metadados'),
        ),
        migrations.AlterField(
            model_name='historicalpublicationstate',
            name='metadados',
            field=models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='metadados'),
        ),
        migrations.AlterField(
            model_name='historicalsaleschannel',
            name='metadados',
            field=models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='metadados'),
        ),
        migrations.AlterField(
            model_name='publicationpolicy',
            name='metadados',
            field=models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='metadados'),
        ),
        migrations.AlterField(
            model_name='publicationstate',
            name='metadados',
            field=models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='metadados'),
        ),
        migrations.AlterField(
            model_name='saleschannel',
            name='metadados',
            field=models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='metadados'),
        ),
    ]
