# Generated by Django 5.1.15 on 2026-10-06 13:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_plataformas_woocommerce_suri'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='dominio_avaliacoes',
            field=models.CharField(blank=True, help_text='Ex.: maxxxmoveis.com.br. Informe o dominio exato, sem https:// ou caminho.', max_length=253, validators=[django.core.validators.DomainNameValidator(accept_idna=False)], verbose_name='dominio da loja para avaliacoes'),
        ),
        migrations.AddField(
            model_name='historicalaccount',
            name='dominio_avaliacoes',
            field=models.CharField(blank=True, help_text='Ex.: maxxxmoveis.com.br. Informe o dominio exato, sem https:// ou caminho.', max_length=253, validators=[django.core.validators.DomainNameValidator(accept_idna=False)], verbose_name='dominio da loja para avaliacoes'),
        ),
    ]
