# Generated by Django 5.1.15 on 2026-10-06 16:16

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_dominio_avaliacoes_padrao_banco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='dominio_avaliacoes',
            field=models.CharField(blank=True, db_default='', default='', help_text='Ex.: minhaloja.com.br, www.minhaloja.com.br. Um ou mais dominios exatos, separados por virgula, sem https:// ou caminho.', max_length=1000, validators=[apps.core.validators.validar_dominios], verbose_name='dominios da loja para avaliacoes'),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='dominio_avaliacoes',
            field=models.CharField(blank=True, db_default='', default='', help_text='Ex.: minhaloja.com.br, www.minhaloja.com.br. Um ou mais dominios exatos, separados por virgula, sem https:// ou caminho.', max_length=1000, validators=[apps.core.validators.validar_dominios], verbose_name='dominios da loja para avaliacoes'),
        ),
    ]
