# Generated by Django 5.1.15 on 2026-09-29 10:04

import apps.integracoes.permissoes
import django.core.validators
import django.db.models.deletion
import django.db.models.manager
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_grupos_e_perfis_padrao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoIntegracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('origin', models.CharField(choices=[('starhub', 'StarHub'), ('shopify', 'Shopify'), ('woocommerce', 'WooCommerce'), ('mercado_livre', 'Mercado Livre'), ('shopee', 'Shopee'), ('amazon', 'Amazon'), ('magalu', 'Magalu'), ('api', 'API'), ('import', 'Importacao')], default='starhub', max_length=30, verbose_name='origem')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='alterado em')),
                ('metadados', models.JSONField(blank=True, default=list, verbose_name='metadados')),
                ('nome', models.CharField(default='Shopify', max_length=150, verbose_name='nome')),
                ('plataforma', models.CharField(choices=[('shopify', 'Shopify')], default='shopify', max_length=30, verbose_name='plataforma')),
                ('dominio_loja', models.CharField(blank=True, max_length=255, verbose_name='dominio da loja')),
                ('versao_api', models.CharField(default='2026-07', max_length=20, verbose_name='versao da API')),
                ('client_id', models.CharField(blank=True, max_length=255, verbose_name='Client ID')),
                ('token_criptografado', models.TextField(blank=True, editable=False)),
                ('segredo_criptografado', models.TextField(blank=True, editable=False)),
                ('url_webhook', models.URLField(blank=True, verbose_name='URL publica dos webhooks')),
                ('permissoes', models.JSONField(blank=True, default=apps.integracoes.permissoes.matriz_vazia, verbose_name='permissoes')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.account', verbose_name='conta')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='alterado por')),
            ],
            options={
                'verbose_name': 'configuracao de integracao',
                'verbose_name_plural': 'Configuracao Shopify',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ExecucaoIntegracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('origin', models.CharField(choices=[('starhub', 'StarHub'), ('shopify', 'Shopify'), ('woocommerce', 'WooCommerce'), ('mercado_livre', 'Mercado Livre'), ('shopee', 'Shopee'), ('amazon', 'Amazon'), ('magalu', 'Magalu'), ('api', 'API'), ('import', 'Importacao')], default='starhub', max_length=30, verbose_name='origem')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='alterado em')),
                ('metadados', models.JSONField(blank=True, default=list, verbose_name='metadados')),
                ('tipo', models.CharField(choices=[('sync', 'Sincronizar loja'), ('webhooks', 'Cadastrar webhooks'), ('receive', 'Receber webhook')], max_length=20, verbose_name='tarefa')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('running', 'Processando'), ('completed', 'Concluida'), ('failed', 'Falhou')], db_index=True, default='pending', max_length=20)),
                ('celery_task_id', models.CharField(blank=True, max_length=255, verbose_name='ID no Celery')),
                ('etapa', models.CharField(default='Aguardando', max_length=150)),
                ('processados', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('progresso', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('mensagem', models.TextField(blank=True)),
                ('iniciada_em', models.DateTimeField(blank=True, null=True)),
                ('concluida_em', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.account', verbose_name='conta')),
                ('configuracao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='execucoes', to='integracoes.configuracaointegracao')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='alterado por')),
            ],
            options={
                'verbose_name': 'tarefa de integracao',
                'verbose_name_plural': 'Tarefas de integracao',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalConfiguracaoIntegracao',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('active', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('origin', models.CharField(choices=[('starhub', 'StarHub'), ('shopify', 'Shopify'), ('woocommerce', 'WooCommerce'), ('mercado_livre', 'Mercado Livre'), ('shopee', 'Shopee'), ('amazon', 'Amazon'), ('magalu', 'Magalu'), ('api', 'API'), ('import', 'Importacao')], default='starhub', max_length=30, verbose_name='origem')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='alterado em')),
                ('metadados', models.JSONField(blank=True, default=list, verbose_name='metadados')),
                ('nome', models.CharField(default='Shopify', max_length=150, verbose_name='nome')),
                ('plataforma', models.CharField(choices=[('shopify', 'Shopify')], default='shopify', max_length=30, verbose_name='plataforma')),
                ('dominio_loja', models.CharField(blank=True, max_length=255, verbose_name='dominio da loja')),
                ('versao_api', models.CharField(default='2026-07', max_length=20, verbose_name='versao da API')),
                ('client_id', models.CharField(blank=True, max_length=255, verbose_name='Client ID')),
                ('token_criptografado', models.TextField(blank=True, editable=False)),
                ('segredo_criptografado', models.TextField(blank=True, editable=False)),
                ('url_webhook', models.URLField(blank=True, verbose_name='URL publica dos webhooks')),
                ('permissoes', models.JSONField(blank=True, default=apps.integracoes.permissoes.matriz_vazia, verbose_name='permissoes')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('account', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.account', verbose_name='conta')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='alterado por')),
            ],
            options={
                'verbose_name': 'historical configuracao de integracao',
                'verbose_name_plural': 'historical Configuracao Shopify',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalExecucaoIntegracao',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('active', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('origin', models.CharField(choices=[('starhub', 'StarHub'), ('shopify', 'Shopify'), ('woocommerce', 'WooCommerce'), ('mercado_livre', 'Mercado Livre'), ('shopee', 'Shopee'), ('amazon', 'Amazon'), ('magalu', 'Magalu'), ('api', 'API'), ('import', 'Importacao')], default='starhub', max_length=30, verbose_name='origem')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='alterado em')),
                ('metadados', models.JSONField(blank=True, default=list, verbose_name='metadados')),
                ('tipo', models.CharField(choices=[('sync', 'Sincronizar loja'), ('webhooks', 'Cadastrar webhooks'), ('receive', 'Receber webhook')], max_length=20, verbose_name='tarefa')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('running', 'Processando'), ('completed', 'Concluida'), ('failed', 'Falhou')], db_index=True, default='pending', max_length=20)),
                ('celery_task_id', models.CharField(blank=True, max_length=255, verbose_name='ID no Celery')),
                ('etapa', models.CharField(default='Aguardando', max_length=150)),
                ('processados', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('progresso', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('mensagem', models.TextField(blank=True)),
                ('iniciada_em', models.DateTimeField(blank=True, null=True)),
                ('concluida_em', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('account', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.account', verbose_name='conta')),
                ('configuracao', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='integracoes.configuracaointegracao')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='alterado por')),
            ],
            options={
                'verbose_name': 'historical tarefa de integracao',
                'verbose_name_plural': 'historical Tarefas de integracao',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddConstraint(
            model_name='configuracaointegracao',
            constraint=models.UniqueConstraint(fields=('account', 'plataforma'), name='integracao_plataforma_conta_unica'),
        ),
    ]
