# Generated by Django 5.1.15 on 2026-09-29 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integracoes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracaointegracao',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='historicalconfiguracaointegracao',
            name='client_id',
        ),
    ]
