# Generated by Django 5.1.15 on 2026-09-30 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracoes', '0002_remove_configuracaointegracao_client_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execucaointegracao',
            name='tipo',
            field=models.CharField(choices=[('sync', 'Sincronizar loja'), ('webhooks', 'Cadastrar webhooks'), ('receive', 'Receber webhook'), ('send', 'Enviar alteracao')], max_length=20, verbose_name='tarefa'),
        ),
        migrations.AlterField(
            model_name='historicalexecucaointegracao',
            name='tipo',
            field=models.CharField(choices=[('sync', 'Sincronizar loja'), ('webhooks', 'Cadastrar webhooks'), ('receive', 'Receber webhook'), ('send', 'Enviar alteracao')], max_length=20, verbose_name='tarefa'),
        ),
    ]
