# Generated by Django 5.1.15 on 2026-09-30 18:31

from django.conf import settings
from django.db import migrations, models


def interromper_duplicadas(apps, schema_editor):
    # O indice unico nao cria com duas sincronizacoes abertas da mesma loja: fica a
    # mais nova (a que o operador espera ver), as outras viram falha com o motivo.
    Execucao = apps.get_model("integracoes", "ExecucaoIntegracao")
    abertas = Execucao.objects.filter(
        status__in=["pending", "running"], tipo="sync"
    ).order_by("configuracao_id", "-created_at", "-pk")
    vistas = set()
    antigas = []
    for pk, configuracao_id in abertas.values_list("pk", "configuracao_id"):
        if configuracao_id in vistas:
            antigas.append(pk)
        vistas.add(configuracao_id)
    Execucao.objects.filter(pk__in=antigas).update(
        status="failed", etapa="Falhou",
        mensagem="Interrompida: outra sincronizacao da mesma loja estava aberta.",
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_grupos_e_perfis_padrao'),
        ('integracoes', '0003_execucao_tipo_enviar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='execucaointegracao',
            name='parametros',
            field=models.JSONField(blank=True, default=dict, verbose_name='parametros'),
        ),
        migrations.AddField(
            model_name='historicalexecucaointegracao',
            name='parametros',
            field=models.JSONField(blank=True, default=dict, verbose_name='parametros'),
        ),
        migrations.AlterField(
            model_name='execucaointegracao',
            name='tipo',
            field=models.CharField(choices=[('sync', 'Sincronizar loja'), ('webhooks', 'Cadastrar webhooks'), ('receive', 'Receber webhook'), ('send', 'Enviar alteracao'), ('export', 'Exportar dados')], max_length=20, verbose_name='tarefa'),
        ),
        migrations.AlterField(
            model_name='historicalexecucaointegracao',
            name='tipo',
            field=models.CharField(choices=[('sync', 'Sincronizar loja'), ('webhooks', 'Cadastrar webhooks'), ('receive', 'Receber webhook'), ('send', 'Enviar alteracao'), ('export', 'Exportar dados')], max_length=20, verbose_name='tarefa'),
        ),
        migrations.RunPython(interromper_duplicadas, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='execucaointegracao',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'running']), ('tipo__in', ['sync', 'export'])), fields=('configuracao',), name='integracao_uma_sincronizacao_por_vez'),
        ),
    ]
