# Generated by Django 5.1.15 on 2026-10-01 08:01

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracoes', '0004_execucao_parametros_exportar'),
    ]

    operations = [
        migrations.AddField(
            model_name='execucaointegracao',
            name='falhas',
            field=models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='falhas'),
        ),
        migrations.AddField(
            model_name='historicalexecucaointegracao',
            name='falhas',
            field=models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='falhas'),
        ),
        migrations.AlterField(
            model_name='configuracaointegracao',
            name='metadados',
            field=models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='metadados'),
        ),
        migrations.AlterField(
            model_name='execucaointegracao',
            name='metadados',
            field=models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='metadados'),
        ),
        migrations.AlterField(
            model_name='execucaointegracao',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('running', 'Processando'), ('completed', 'Concluida'), ('completed_errors', 'Concluida com falhas'), ('failed', 'Falhou')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalconfiguracaointegracao',
            name='metadados',
            field=models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='metadados'),
        ),
        migrations.AlterField(
            model_name='historicalexecucaointegracao',
            name='metadados',
            field=models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='metadados'),
        ),
        migrations.AlterField(
            model_name='historicalexecucaointegracao',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('running', 'Processando'), ('completed', 'Concluida'), ('completed_errors', 'Concluida com falhas'), ('failed', 'Falhou')], db_index=True, default='pending', max_length=20),
        ),
    ]
