# Generated by Django 5.1.15 on 2026-10-03 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracoes', '0008_uuid_unico'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaointegracao',
            name='segredo_avaliacoes_criptografado',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='historicalconfiguracaointegracao',
            name='segredo_avaliacoes_criptografado',
            field=models.TextField(blank=True, editable=False),
        ),
    ]
