# Generated by Django 5.1.15 on 2026-10-04 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracoes', '0010_tipo_importar_avaliacoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execucaointegracao',
            name='configuracao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='execucoes', to='integracoes.configuracaointegracao'),
        ),
        migrations.AlterField(
            model_name='execucaointegracao',
            name='tipo',
            field=models.CharField(choices=[('sync', 'Sincronizar loja'), ('webhooks', 'Cadastrar webhooks'), ('receive', 'Receber webhook'), ('send', 'Enviar alteracao'), ('export', 'Exportar dados'), ('import_reviews', 'Importar avaliacoes'), ('import_freight', 'Importar faixas de frete')], max_length=20, verbose_name='tarefa'),
        ),
        migrations.AlterField(
            model_name='historicalexecucaointegracao',
            name='tipo',
            field=models.CharField(choices=[('sync', 'Sincronizar loja'), ('webhooks', 'Cadastrar webhooks'), ('receive', 'Receber webhook'), ('send', 'Enviar alteracao'), ('export', 'Exportar dados'), ('import_reviews', 'Importar avaliacoes'), ('import_freight', 'Importar faixas de frete')], max_length=20, verbose_name='tarefa'),
        ),
    ]
