# Generated by Django 5.1.15 on 2026-10-04 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integracoes', '0011_tarefa_sem_loja'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracaointegracao',
            options={'verbose_name': 'configuracao de integracao', 'verbose_name_plural': 'Shopify'},
        ),
        migrations.AlterModelOptions(
            name='execucaointegracao',
            options={'ordering': ['-created_at'], 'verbose_name': 'tarefa', 'verbose_name_plural': 'Tarefas'},
        ),
        migrations.AlterModelOptions(
            name='historicalconfiguracaointegracao',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical configuracao de integracao', 'verbose_name_plural': 'historical Shopify'},
        ),
        migrations.AlterModelOptions(
            name='historicalexecucaointegracao',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical tarefa', 'verbose_name_plural': 'historical Tarefas'},
        ),
    ]
