# Generated by Django 5.1.15 on 2026-10-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracoes', '0012_nomes_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execucaointegracao',
            name='tipo',
            field=models.CharField(choices=[('sync', 'Sincronizar loja'), ('webhooks', 'Cadastrar webhooks'), ('receive', 'Receber webhook'), ('send', 'Enviar alteracao'), ('export', 'Exportar dados'), ('import_reviews', 'Importar avaliacoes'), ('import_freight', 'Importar faixas de frete'), ('carrier', 'Cadastrar frete no checkout')], max_length=20, verbose_name='tarefa'),
        ),
        migrations.AlterField(
            model_name='historicalexecucaointegracao',
            name='tipo',
            field=models.CharField(choices=[('sync', 'Sincronizar loja'), ('webhooks', 'Cadastrar webhooks'), ('receive', 'Receber webhook'), ('send', 'Enviar alteracao'), ('export', 'Exportar dados'), ('import_reviews', 'Importar avaliacoes'), ('import_freight', 'Importar faixas de frete'), ('carrier', 'Cadastrar frete no checkout')], max_length=20, verbose_name='tarefa'),
        ),
    ]
