# Generated by Django 5.1.15 on 2026-10-04 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracoes', '0014_tipo_verificar_frete'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaointegracao',
            name='frete_ativo',
            field=models.BooleanField(default=True, verbose_name='frete do hub no checkout'),
        ),
        migrations.AddField(
            model_name='historicalconfiguracaointegracao',
            name='frete_ativo',
            field=models.BooleanField(default=True, verbose_name='frete do hub no checkout'),
        ),
    ]
