# Generated by Django 5.1.15 on 2026-10-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracoes', '0015_frete_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaointegracao',
            name='origin',
            field=models.CharField(choices=[('starhub', 'StarHub'), ('shopify', 'Shopify'), ('woocommerce', 'WooCommerce'), ('suri', 'Suri Shop'), ('mercado_livre', 'Mercado Livre'), ('shopee', 'Shopee'), ('amazon', 'Amazon'), ('magalu', 'Magalu'), ('api', 'API'), ('import', 'Importacao')], default='starhub', max_length=30, verbose_name='origem'),
        ),
        migrations.AlterField(
            model_name='configuracaointegracao',
            name='plataforma',
            field=models.CharField(choices=[('shopify', 'Shopify'), ('woocommerce', 'WooCommerce'), ('suri', 'Suri Shop')], default='shopify', max_length=30, verbose_name='plataforma'),
        ),
        migrations.AlterField(
            model_name='execucaointegracao',
            name='origin',
            field=models.CharField(choices=[('starhub', 'StarHub'), ('shopify', 'Shopify'), ('woocommerce', 'WooCommerce'), ('suri', 'Suri Shop'), ('mercado_livre', 'Mercado Livre'), ('shopee', 'Shopee'), ('amazon', 'Amazon'), ('magalu', 'Magalu'), ('api', 'API'), ('import', 'Importacao')], default='starhub', max_length=30, verbose_name='origem'),
        ),
        migrations.AlterField(
            model_name='historicalconfiguracaointegracao',
            name='origin',
            field=models.CharField(choices=[('starhub', 'StarHub'), ('shopify', 'Shopify'), ('woocommerce', 'WooCommerce'), ('suri', 'Suri Shop'), ('mercado_livre', 'Mercado Livre'), ('shopee', 'Shopee'), ('amazon', 'Amazon'), ('magalu', 'Magalu'), ('api', 'API'), ('import', 'Importacao')], default='starhub', max_length=30, verbose_name='origem'),
        ),
        migrations.AlterField(
            model_name='historicalconfiguracaointegracao',
            name='plataforma',
            field=models.CharField(choices=[('shopify', 'Shopify'), ('woocommerce', 'WooCommerce'), ('suri', 'Suri Shop')], default='shopify', max_length=30, verbose_name='plataforma'),
        ),
        migrations.AlterField(
            model_name='historicalexecucaointegracao',
            name='origin',
            field=models.CharField(choices=[('starhub', 'StarHub'), ('shopify', 'Shopify'), ('woocommerce', 'WooCommerce'), ('suri', 'Suri Shop'), ('mercado_livre', 'Mercado Livre'), ('shopee', 'Shopee'), ('amazon', 'Amazon'), ('magalu', 'Magalu'), ('api', 'API'), ('import', 'Importacao')], default='starhub', max_length=30, verbose_name='origem'),
        ),
    ]
