# Generated by Django 5.1.15 on 2026-10-05 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracoes', '0016_plataformas_woocommerce_suri'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaointegracao',
            name='encaminhar_pedidos',
            field=models.BooleanField(default=False, help_text='Desligado, a API Woo do hub responde os pedidos com os dados do hub. Ligado, cada chamada de pedido do ERP vai para a loja WooCommerce e a resposta dela volta ao ERP; cada uma fica em Tarefas, com a requisicao e a resposta.', verbose_name='encaminhar pedidos do ERP a loja'),
        ),
        migrations.AddField(
            model_name='historicalconfiguracaointegracao',
            name='encaminhar_pedidos',
            field=models.BooleanField(default=False, help_text='Desligado, a API Woo do hub responde os pedidos com os dados do hub. Ligado, cada chamada de pedido do ERP vai para a loja WooCommerce e a resposta dela volta ao ERP; cada uma fica em Tarefas, com a requisicao e a resposta.', verbose_name='encaminhar pedidos do ERP a loja'),
        ),
        migrations.AlterField(
            model_name='execucaointegracao',
            name='tipo',
            field=models.CharField(choices=[('sync', 'Sincronizar loja'), ('webhooks', 'Cadastrar webhooks'), ('receive', 'Receber webhook'), ('send', 'Enviar alteracao'), ('export', 'Exportar dados'), ('import_reviews', 'Importar avaliacoes'), ('import_freight', 'Importar faixas de frete'), ('carrier', 'Cadastrar frete no checkout'), ('carrier_check', 'Verificar frete no checkout'), ('forward', 'Encaminhar pedido a loja')], max_length=20, verbose_name='tarefa'),
        ),
        migrations.AlterField(
            model_name='historicalexecucaointegracao',
            name='tipo',
            field=models.CharField(choices=[('sync', 'Sincronizar loja'), ('webhooks', 'Cadastrar webhooks'), ('receive', 'Receber webhook'), ('send', 'Enviar alteracao'), ('export', 'Exportar dados'), ('import_reviews', 'Importar avaliacoes'), ('import_freight', 'Importar faixas de frete'), ('carrier', 'Cadastrar frete no checkout'), ('carrier_check', 'Verificar frete no checkout'), ('forward', 'Encaminhar pedido a loja')], max_length=20, verbose_name='tarefa'),
        ),
    ]
