# Generated by Django 5.1.15 on 2026-10-07 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracoes', '0017_encaminhar_pedidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaointegracao',
            name='id_vendedor',
            field=models.PositiveIntegerField(blank=True, help_text='Numero do vendedor no ERP para os pedidos que vem desta loja. Vai no meta_data do pedido como idVendedor.', null=True, verbose_name='ID do vendedor no ERP'),
        ),
        migrations.AddField(
            model_name='historicalconfiguracaointegracao',
            name='id_vendedor',
            field=models.PositiveIntegerField(blank=True, help_text='Numero do vendedor no ERP para os pedidos que vem desta loja. Vai no meta_data do pedido como idVendedor.', null=True, verbose_name='ID do vendedor no ERP'),
        ),
    ]
