# Generated by Django 5.1.15 on 2026-09-28 04:02

import django.db.models.deletion
import django.db.models.manager
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChaveApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('origin', models.CharField(choices=[('starhub', 'StarHub'), ('shopify', 'Shopify'), ('woocommerce', 'WooCommerce'), ('mercado_livre', 'Mercado Livre'), ('shopee', 'Shopee'), ('amazon', 'Amazon'), ('magalu', 'Magalu'), ('api', 'API'), ('import', 'Importacao')], default='starhub', max_length=30, verbose_name='origem')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='alterado em')),
                ('metadados', models.JSONField(blank=True, default=list, verbose_name='metadados')),
                ('descricao', models.CharField(max_length=200, verbose_name='descricao')),
                ('permissao', models.CharField(choices=[('read', 'Leitura'), ('write', 'Escrita'), ('read_write', 'Leitura e escrita')], default='read_write', max_length=10, verbose_name='permissao')),
                ('chave_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('segredo_hash', models.CharField(editable=False, max_length=64)),
                ('final_chave', models.CharField(editable=False, max_length=7, verbose_name='final da chave')),
                ('last_used_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='ultimo acesso')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expira em')),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.account', verbose_name='conta')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'chave de API',
                'verbose_name_plural': 'chaves de API',
                'ordering': ['-created_at'],
                'permissions': [('usar_api', 'Pode usar a API Woo com login JWT')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalChaveApi',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('active', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('origin', models.CharField(choices=[('starhub', 'StarHub'), ('shopify', 'Shopify'), ('woocommerce', 'WooCommerce'), ('mercado_livre', 'Mercado Livre'), ('shopee', 'Shopee'), ('amazon', 'Amazon'), ('magalu', 'Magalu'), ('api', 'API'), ('import', 'Importacao')], default='starhub', max_length=30, verbose_name='origem')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='alterado em')),
                ('metadados', models.JSONField(blank=True, default=list, verbose_name='metadados')),
                ('descricao', models.CharField(max_length=200, verbose_name='descricao')),
                ('permissao', models.CharField(choices=[('read', 'Leitura'), ('write', 'Escrita'), ('read_write', 'Leitura e escrita')], default='read_write', max_length=10, verbose_name='permissao')),
                ('chave_hash', models.CharField(db_index=True, editable=False, max_length=64)),
                ('segredo_hash', models.CharField(editable=False, max_length=64)),
                ('final_chave', models.CharField(editable=False, max_length=7, verbose_name='final da chave')),
                ('last_used_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='ultimo acesso')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expira em')),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('account', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.account', verbose_name='conta')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical chave de API',
                'verbose_name_plural': 'historical chaves de API',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
