# Generated by Django 5.1.15 on 2026-10-01 08:01

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woo_api', '0002_rotulos_ptbr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaveapi',
            name='metadados',
            field=models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='metadados'),
        ),
        migrations.AlterField(
            model_name='historicalchaveapi',
            name='metadados',
            field=models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='metadados'),
        ),
    ]
